// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AppNotification;
@class AppNotification_Builder;

@interface AppNotificationSpecificsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface AppNotification : PBGeneratedMessage {
@private
  BOOL hasCreationTimestampMs_:1;
  BOOL hasGuid_:1;
  BOOL hasAppId_:1;
  BOOL hasTitle_:1;
  BOOL hasBodyText_:1;
  BOOL hasLinkUrl_:1;
  BOOL hasLinkText_:1;
  int64_t creationTimestampMs;
  NSString* guid;
  NSString* appId;
  NSString* title;
  NSString* bodyText;
  NSString* linkUrl;
  NSString* linkText;
}
- (BOOL) hasGuid;
- (BOOL) hasAppId;
- (BOOL) hasCreationTimestampMs;
- (BOOL) hasTitle;
- (BOOL) hasBodyText;
- (BOOL) hasLinkUrl;
- (BOOL) hasLinkText;
@property (readonly, retain) NSString* guid;
@property (readonly, retain) NSString* appId;
@property (readonly) int64_t creationTimestampMs;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* bodyText;
@property (readonly, retain) NSString* linkUrl;
@property (readonly, retain) NSString* linkText;

+ (AppNotification*) defaultInstance;
- (AppNotification*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppNotification_Builder*) builder;
+ (AppNotification_Builder*) builder;
+ (AppNotification_Builder*) builderWithPrototype:(AppNotification*) prototype;

+ (AppNotification*) parseFromData:(NSData*) data;
+ (AppNotification*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppNotification*) parseFromInputStream:(NSInputStream*) input;
+ (AppNotification*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppNotification*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppNotification*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppNotification_Builder : PBGeneratedMessage_Builder {
@private
  AppNotification* result;
}

- (AppNotification*) defaultInstance;

- (AppNotification_Builder*) clear;
- (AppNotification_Builder*) clone;

- (AppNotification*) build;
- (AppNotification*) buildPartial;

- (AppNotification_Builder*) mergeFrom:(AppNotification*) other;
- (AppNotification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppNotification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGuid;
- (NSString*) guid;
- (AppNotification_Builder*) setGuid:(NSString*) value;
- (AppNotification_Builder*) clearGuid;

- (BOOL) hasAppId;
- (NSString*) appId;
- (AppNotification_Builder*) setAppId:(NSString*) value;
- (AppNotification_Builder*) clearAppId;

- (BOOL) hasCreationTimestampMs;
- (int64_t) creationTimestampMs;
- (AppNotification_Builder*) setCreationTimestampMs:(int64_t) value;
- (AppNotification_Builder*) clearCreationTimestampMs;

- (BOOL) hasTitle;
- (NSString*) title;
- (AppNotification_Builder*) setTitle:(NSString*) value;
- (AppNotification_Builder*) clearTitle;

- (BOOL) hasBodyText;
- (NSString*) bodyText;
- (AppNotification_Builder*) setBodyText:(NSString*) value;
- (AppNotification_Builder*) clearBodyText;

- (BOOL) hasLinkUrl;
- (NSString*) linkUrl;
- (AppNotification_Builder*) setLinkUrl:(NSString*) value;
- (AppNotification_Builder*) clearLinkUrl;

- (BOOL) hasLinkText;
- (NSString*) linkText;
- (AppNotification_Builder*) setLinkText:(NSString*) value;
- (AppNotification_Builder*) clearLinkText;
@end

