// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "AppNotificationSpecifics.pb.h"

@implementation AppNotificationSpecificsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [AppNotificationSpecificsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface AppNotification ()
@property (retain) NSString* guid;
@property (retain) NSString* appId;
@property int64_t creationTimestampMs;
@property (retain) NSString* title;
@property (retain) NSString* bodyText;
@property (retain) NSString* linkUrl;
@property (retain) NSString* linkText;
@end

@implementation AppNotification

- (BOOL) hasGuid {
  return !!hasGuid_;
}
- (void) setHasGuid:(BOOL) value {
  hasGuid_ = !!value;
}
@synthesize guid;
- (BOOL) hasAppId {
  return !!hasAppId_;
}
- (void) setHasAppId:(BOOL) value {
  hasAppId_ = !!value;
}
@synthesize appId;
- (BOOL) hasCreationTimestampMs {
  return !!hasCreationTimestampMs_;
}
- (void) setHasCreationTimestampMs:(BOOL) value {
  hasCreationTimestampMs_ = !!value;
}
@synthesize creationTimestampMs;
- (BOOL) hasTitle {
  return !!hasTitle_;
}
- (void) setHasTitle:(BOOL) value {
  hasTitle_ = !!value;
}
@synthesize title;
- (BOOL) hasBodyText {
  return !!hasBodyText_;
}
- (void) setHasBodyText:(BOOL) value {
  hasBodyText_ = !!value;
}
@synthesize bodyText;
- (BOOL) hasLinkUrl {
  return !!hasLinkUrl_;
}
- (void) setHasLinkUrl:(BOOL) value {
  hasLinkUrl_ = !!value;
}
@synthesize linkUrl;
- (BOOL) hasLinkText {
  return !!hasLinkText_;
}
- (void) setHasLinkText:(BOOL) value {
  hasLinkText_ = !!value;
}
@synthesize linkText;
- (void) dealloc {
  self.guid = nil;
  self.appId = nil;
  self.title = nil;
  self.bodyText = nil;
  self.linkUrl = nil;
  self.linkText = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.guid = @"";
    self.appId = @"";
    self.creationTimestampMs = 0L;
    self.title = @"";
    self.bodyText = @"";
    self.linkUrl = @"";
    self.linkText = @"";
  }
  return self;
}
static AppNotification* defaultAppNotificationInstance = nil;
+ (void) initialize {
  if (self == [AppNotification class]) {
    defaultAppNotificationInstance = [[AppNotification alloc] init];
  }
}
+ (AppNotification*) defaultInstance {
  return defaultAppNotificationInstance;
}
- (AppNotification*) defaultInstance {
  return defaultAppNotificationInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasGuid) {
    [output writeString:1 value:self.guid];
  }
  if (self.hasAppId) {
    [output writeString:2 value:self.appId];
  }
  if (self.hasCreationTimestampMs) {
    [output writeInt64:3 value:self.creationTimestampMs];
  }
  if (self.hasTitle) {
    [output writeString:4 value:self.title];
  }
  if (self.hasBodyText) {
    [output writeString:5 value:self.bodyText];
  }
  if (self.hasLinkUrl) {
    [output writeString:6 value:self.linkUrl];
  }
  if (self.hasLinkText) {
    [output writeString:7 value:self.linkText];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasGuid) {
    size += computeStringSize(1, self.guid);
  }
  if (self.hasAppId) {
    size += computeStringSize(2, self.appId);
  }
  if (self.hasCreationTimestampMs) {
    size += computeInt64Size(3, self.creationTimestampMs);
  }
  if (self.hasTitle) {
    size += computeStringSize(4, self.title);
  }
  if (self.hasBodyText) {
    size += computeStringSize(5, self.bodyText);
  }
  if (self.hasLinkUrl) {
    size += computeStringSize(6, self.linkUrl);
  }
  if (self.hasLinkText) {
    size += computeStringSize(7, self.linkText);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (AppNotification*) parseFromData:(NSData*) data {
  return (AppNotification*)[[[AppNotification builder] mergeFromData:data] build];
}
+ (AppNotification*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AppNotification*)[[[AppNotification builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (AppNotification*) parseFromInputStream:(NSInputStream*) input {
  return (AppNotification*)[[[AppNotification builder] mergeFromInputStream:input] build];
}
+ (AppNotification*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AppNotification*)[[[AppNotification builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (AppNotification*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (AppNotification*)[[[AppNotification builder] mergeFromCodedInputStream:input] build];
}
+ (AppNotification*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AppNotification*)[[[AppNotification builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (AppNotification_Builder*) builder {
  return [[[AppNotification_Builder alloc] init] autorelease];
}
+ (AppNotification_Builder*) builderWithPrototype:(AppNotification*) prototype {
  return [[AppNotification builder] mergeFrom:prototype];
}
- (AppNotification_Builder*) builder {
  return [AppNotification builder];
}
@end

@interface AppNotification_Builder()
@property (retain) AppNotification* result;
@end

@implementation AppNotification_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[AppNotification alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (AppNotification_Builder*) clear {
  self.result = [[[AppNotification alloc] init] autorelease];
  return self;
}
- (AppNotification_Builder*) clone {
  return [AppNotification builderWithPrototype:result];
}
- (AppNotification*) defaultInstance {
  return [AppNotification defaultInstance];
}
- (AppNotification*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (AppNotification*) buildPartial {
  AppNotification* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (AppNotification_Builder*) mergeFrom:(AppNotification*) other {
  if (other == [AppNotification defaultInstance]) {
    return self;
  }
  if (other.hasGuid) {
    [self setGuid:other.guid];
  }
  if (other.hasAppId) {
    [self setAppId:other.appId];
  }
  if (other.hasCreationTimestampMs) {
    [self setCreationTimestampMs:other.creationTimestampMs];
  }
  if (other.hasTitle) {
    [self setTitle:other.title];
  }
  if (other.hasBodyText) {
    [self setBodyText:other.bodyText];
  }
  if (other.hasLinkUrl) {
    [self setLinkUrl:other.linkUrl];
  }
  if (other.hasLinkText) {
    [self setLinkText:other.linkText];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (AppNotification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (AppNotification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setGuid:[input readString]];
        break;
      }
      case 18: {
        [self setAppId:[input readString]];
        break;
      }
      case 24: {
        [self setCreationTimestampMs:[input readInt64]];
        break;
      }
      case 34: {
        [self setTitle:[input readString]];
        break;
      }
      case 42: {
        [self setBodyText:[input readString]];
        break;
      }
      case 50: {
        [self setLinkUrl:[input readString]];
        break;
      }
      case 58: {
        [self setLinkText:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasGuid {
  return result.hasGuid;
}
- (NSString*) guid {
  return result.guid;
}
- (AppNotification_Builder*) setGuid:(NSString*) value {
  result.hasGuid = YES;
  result.guid = value;
  return self;
}
- (AppNotification_Builder*) clearGuid {
  result.hasGuid = NO;
  result.guid = @"";
  return self;
}
- (BOOL) hasAppId {
  return result.hasAppId;
}
- (NSString*) appId {
  return result.appId;
}
- (AppNotification_Builder*) setAppId:(NSString*) value {
  result.hasAppId = YES;
  result.appId = value;
  return self;
}
- (AppNotification_Builder*) clearAppId {
  result.hasAppId = NO;
  result.appId = @"";
  return self;
}
- (BOOL) hasCreationTimestampMs {
  return result.hasCreationTimestampMs;
}
- (int64_t) creationTimestampMs {
  return result.creationTimestampMs;
}
- (AppNotification_Builder*) setCreationTimestampMs:(int64_t) value {
  result.hasCreationTimestampMs = YES;
  result.creationTimestampMs = value;
  return self;
}
- (AppNotification_Builder*) clearCreationTimestampMs {
  result.hasCreationTimestampMs = NO;
  result.creationTimestampMs = 0L;
  return self;
}
- (BOOL) hasTitle {
  return result.hasTitle;
}
- (NSString*) title {
  return result.title;
}
- (AppNotification_Builder*) setTitle:(NSString*) value {
  result.hasTitle = YES;
  result.title = value;
  return self;
}
- (AppNotification_Builder*) clearTitle {
  result.hasTitle = NO;
  result.title = @"";
  return self;
}
- (BOOL) hasBodyText {
  return result.hasBodyText;
}
- (NSString*) bodyText {
  return result.bodyText;
}
- (AppNotification_Builder*) setBodyText:(NSString*) value {
  result.hasBodyText = YES;
  result.bodyText = value;
  return self;
}
- (AppNotification_Builder*) clearBodyText {
  result.hasBodyText = NO;
  result.bodyText = @"";
  return self;
}
- (BOOL) hasLinkUrl {
  return result.hasLinkUrl;
}
- (NSString*) linkUrl {
  return result.linkUrl;
}
- (AppNotification_Builder*) setLinkUrl:(NSString*) value {
  result.hasLinkUrl = YES;
  result.linkUrl = value;
  return self;
}
- (AppNotification_Builder*) clearLinkUrl {
  result.hasLinkUrl = NO;
  result.linkUrl = @"";
  return self;
}
- (BOOL) hasLinkText {
  return result.hasLinkText;
}
- (NSString*) linkText {
  return result.linkText;
}
- (AppNotification_Builder*) setLinkText:(NSString*) value {
  result.hasLinkText = YES;
  result.linkText = value;
  return self;
}
- (AppNotification_Builder*) clearLinkText {
  result.hasLinkText = NO;
  result.linkText = @"";
  return self;
}
@end

