// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AutofillProfileSpecifics;
@class AutofillProfileSpecifics_Builder;
@class AutofillSpecifics;
@class AutofillSpecifics_Builder;

@interface AutofillSpecificsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface AutofillProfileSpecifics : PBGeneratedMessage {
@private
  BOOL hasLabel_:1;
  BOOL hasGuid_:1;
  BOOL hasCompanyName_:1;
  BOOL hasAddressHomeLine1_:1;
  BOOL hasAddressHomeLine2_:1;
  BOOL hasAddressHomeCity_:1;
  BOOL hasAddressHomeState_:1;
  BOOL hasAddressHomeZip_:1;
  BOOL hasAddressHomeCountry_:1;
  BOOL hasPhoneFaxWholeNumber_:1;
  NSString* label;
  NSString* guid;
  NSString* companyName;
  NSString* addressHomeLine1;
  NSString* addressHomeLine2;
  NSString* addressHomeCity;
  NSString* addressHomeState;
  NSString* addressHomeZip;
  NSString* addressHomeCountry;
  NSString* phoneFaxWholeNumber;
  NSMutableArray* mutableNameFirstList;
  NSMutableArray* mutableNameMiddleList;
  NSMutableArray* mutableNameLastList;
  NSMutableArray* mutableEmailAddressList;
  NSMutableArray* mutablePhoneHomeWholeNumberList;
}
- (BOOL) hasLabel;
- (BOOL) hasGuid;
- (BOOL) hasCompanyName;
- (BOOL) hasAddressHomeLine1;
- (BOOL) hasAddressHomeLine2;
- (BOOL) hasAddressHomeCity;
- (BOOL) hasAddressHomeState;
- (BOOL) hasAddressHomeZip;
- (BOOL) hasAddressHomeCountry;
- (BOOL) hasPhoneFaxWholeNumber;
@property (readonly, retain) NSString* label;
@property (readonly, retain) NSString* guid;
@property (readonly, retain) NSString* companyName;
@property (readonly, retain) NSString* addressHomeLine1;
@property (readonly, retain) NSString* addressHomeLine2;
@property (readonly, retain) NSString* addressHomeCity;
@property (readonly, retain) NSString* addressHomeState;
@property (readonly, retain) NSString* addressHomeZip;
@property (readonly, retain) NSString* addressHomeCountry;
@property (readonly, retain) NSString* phoneFaxWholeNumber;
- (NSArray*) nameFirstList;
- (NSString*) nameFirstAtIndex:(int32_t) index;
- (NSArray*) nameMiddleList;
- (NSString*) nameMiddleAtIndex:(int32_t) index;
- (NSArray*) nameLastList;
- (NSString*) nameLastAtIndex:(int32_t) index;
- (NSArray*) emailAddressList;
- (NSString*) emailAddressAtIndex:(int32_t) index;
- (NSArray*) phoneHomeWholeNumberList;
- (NSString*) phoneHomeWholeNumberAtIndex:(int32_t) index;

+ (AutofillProfileSpecifics*) defaultInstance;
- (AutofillProfileSpecifics*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AutofillProfileSpecifics_Builder*) builder;
+ (AutofillProfileSpecifics_Builder*) builder;
+ (AutofillProfileSpecifics_Builder*) builderWithPrototype:(AutofillProfileSpecifics*) prototype;

+ (AutofillProfileSpecifics*) parseFromData:(NSData*) data;
+ (AutofillProfileSpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AutofillProfileSpecifics*) parseFromInputStream:(NSInputStream*) input;
+ (AutofillProfileSpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AutofillProfileSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AutofillProfileSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AutofillProfileSpecifics_Builder : PBGeneratedMessage_Builder {
@private
  AutofillProfileSpecifics* result;
}

- (AutofillProfileSpecifics*) defaultInstance;

- (AutofillProfileSpecifics_Builder*) clear;
- (AutofillProfileSpecifics_Builder*) clone;

- (AutofillProfileSpecifics*) build;
- (AutofillProfileSpecifics*) buildPartial;

- (AutofillProfileSpecifics_Builder*) mergeFrom:(AutofillProfileSpecifics*) other;
- (AutofillProfileSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AutofillProfileSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLabel;
- (NSString*) label;
- (AutofillProfileSpecifics_Builder*) setLabel:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearLabel;

- (BOOL) hasGuid;
- (NSString*) guid;
- (AutofillProfileSpecifics_Builder*) setGuid:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearGuid;

- (NSArray*) nameFirstList;
- (NSString*) nameFirstAtIndex:(int32_t) index;
- (AutofillProfileSpecifics_Builder*) replaceNameFirstAtIndex:(int32_t) index with:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addNameFirst:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addAllNameFirst:(NSArray*) values;
- (AutofillProfileSpecifics_Builder*) clearNameFirstList;

- (NSArray*) nameMiddleList;
- (NSString*) nameMiddleAtIndex:(int32_t) index;
- (AutofillProfileSpecifics_Builder*) replaceNameMiddleAtIndex:(int32_t) index with:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addNameMiddle:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addAllNameMiddle:(NSArray*) values;
- (AutofillProfileSpecifics_Builder*) clearNameMiddleList;

- (NSArray*) nameLastList;
- (NSString*) nameLastAtIndex:(int32_t) index;
- (AutofillProfileSpecifics_Builder*) replaceNameLastAtIndex:(int32_t) index with:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addNameLast:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addAllNameLast:(NSArray*) values;
- (AutofillProfileSpecifics_Builder*) clearNameLastList;

- (NSArray*) emailAddressList;
- (NSString*) emailAddressAtIndex:(int32_t) index;
- (AutofillProfileSpecifics_Builder*) replaceEmailAddressAtIndex:(int32_t) index with:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addEmailAddress:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addAllEmailAddress:(NSArray*) values;
- (AutofillProfileSpecifics_Builder*) clearEmailAddressList;

- (BOOL) hasCompanyName;
- (NSString*) companyName;
- (AutofillProfileSpecifics_Builder*) setCompanyName:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearCompanyName;

- (BOOL) hasAddressHomeLine1;
- (NSString*) addressHomeLine1;
- (AutofillProfileSpecifics_Builder*) setAddressHomeLine1:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearAddressHomeLine1;

- (BOOL) hasAddressHomeLine2;
- (NSString*) addressHomeLine2;
- (AutofillProfileSpecifics_Builder*) setAddressHomeLine2:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearAddressHomeLine2;

- (BOOL) hasAddressHomeCity;
- (NSString*) addressHomeCity;
- (AutofillProfileSpecifics_Builder*) setAddressHomeCity:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearAddressHomeCity;

- (BOOL) hasAddressHomeState;
- (NSString*) addressHomeState;
- (AutofillProfileSpecifics_Builder*) setAddressHomeState:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearAddressHomeState;

- (BOOL) hasAddressHomeZip;
- (NSString*) addressHomeZip;
- (AutofillProfileSpecifics_Builder*) setAddressHomeZip:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearAddressHomeZip;

- (BOOL) hasAddressHomeCountry;
- (NSString*) addressHomeCountry;
- (AutofillProfileSpecifics_Builder*) setAddressHomeCountry:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearAddressHomeCountry;

- (NSArray*) phoneHomeWholeNumberList;
- (NSString*) phoneHomeWholeNumberAtIndex:(int32_t) index;
- (AutofillProfileSpecifics_Builder*) replacePhoneHomeWholeNumberAtIndex:(int32_t) index with:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addPhoneHomeWholeNumber:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) addAllPhoneHomeWholeNumber:(NSArray*) values;
- (AutofillProfileSpecifics_Builder*) clearPhoneHomeWholeNumberList;

- (BOOL) hasPhoneFaxWholeNumber;
- (NSString*) phoneFaxWholeNumber;
- (AutofillProfileSpecifics_Builder*) setPhoneFaxWholeNumber:(NSString*) value;
- (AutofillProfileSpecifics_Builder*) clearPhoneFaxWholeNumber;
@end

@interface AutofillSpecifics : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasValue_:1;
  BOOL hasProfile_:1;
  NSString* name;
  NSString* value;
  AutofillProfileSpecifics* profile;
  NSMutableArray* mutableUsageTimestampList;
}
- (BOOL) hasName;
- (BOOL) hasValue;
- (BOOL) hasProfile;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* value;
@property (readonly, retain) AutofillProfileSpecifics* profile;
- (NSArray*) usageTimestampList;
- (int64_t) usageTimestampAtIndex:(int32_t) index;

+ (AutofillSpecifics*) defaultInstance;
- (AutofillSpecifics*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AutofillSpecifics_Builder*) builder;
+ (AutofillSpecifics_Builder*) builder;
+ (AutofillSpecifics_Builder*) builderWithPrototype:(AutofillSpecifics*) prototype;

+ (AutofillSpecifics*) parseFromData:(NSData*) data;
+ (AutofillSpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AutofillSpecifics*) parseFromInputStream:(NSInputStream*) input;
+ (AutofillSpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AutofillSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AutofillSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AutofillSpecifics_Builder : PBGeneratedMessage_Builder {
@private
  AutofillSpecifics* result;
}

- (AutofillSpecifics*) defaultInstance;

- (AutofillSpecifics_Builder*) clear;
- (AutofillSpecifics_Builder*) clone;

- (AutofillSpecifics*) build;
- (AutofillSpecifics*) buildPartial;

- (AutofillSpecifics_Builder*) mergeFrom:(AutofillSpecifics*) other;
- (AutofillSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AutofillSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (AutofillSpecifics_Builder*) setName:(NSString*) value;
- (AutofillSpecifics_Builder*) clearName;

- (BOOL) hasValue;
- (NSString*) value;
- (AutofillSpecifics_Builder*) setValue:(NSString*) value;
- (AutofillSpecifics_Builder*) clearValue;

- (NSArray*) usageTimestampList;
- (int64_t) usageTimestampAtIndex:(int32_t) index;
- (AutofillSpecifics_Builder*) replaceUsageTimestampAtIndex:(int32_t) index with:(int64_t) value;
- (AutofillSpecifics_Builder*) addUsageTimestamp:(int64_t) value;
- (AutofillSpecifics_Builder*) addAllUsageTimestamp:(NSArray*) values;
- (AutofillSpecifics_Builder*) clearUsageTimestampList;

- (BOOL) hasProfile;
- (AutofillProfileSpecifics*) profile;
- (AutofillSpecifics_Builder*) setProfile:(AutofillProfileSpecifics*) value;
- (AutofillSpecifics_Builder*) setProfileBuilder:(AutofillProfileSpecifics_Builder*) builderForValue;
- (AutofillSpecifics_Builder*) mergeProfile:(AutofillProfileSpecifics*) value;
- (AutofillSpecifics_Builder*) clearProfile;
@end

