// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class BookmarkSpecifics;
@class BookmarkSpecifics_Builder;

@interface BookmarkSpecificsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface BookmarkSpecifics : PBGeneratedMessage {
@private
  BOOL hasUrl_:1;
  BOOL hasTitle_:1;
  BOOL hasFavicon_:1;
  NSString* url;
  NSString* title;
  NSData* favicon;
}
- (BOOL) hasUrl;
- (BOOL) hasFavicon;
- (BOOL) hasTitle;
@property (readonly, retain) NSString* url;
@property (readonly, retain) NSData* favicon;
@property (readonly, retain) NSString* title;

+ (BookmarkSpecifics*) defaultInstance;
- (BookmarkSpecifics*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookmarkSpecifics_Builder*) builder;
+ (BookmarkSpecifics_Builder*) builder;
+ (BookmarkSpecifics_Builder*) builderWithPrototype:(BookmarkSpecifics*) prototype;

+ (BookmarkSpecifics*) parseFromData:(NSData*) data;
+ (BookmarkSpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookmarkSpecifics*) parseFromInputStream:(NSInputStream*) input;
+ (BookmarkSpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BookmarkSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BookmarkSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookmarkSpecifics_Builder : PBGeneratedMessage_Builder {
@private
  BookmarkSpecifics* result;
}

- (BookmarkSpecifics*) defaultInstance;

- (BookmarkSpecifics_Builder*) clear;
- (BookmarkSpecifics_Builder*) clone;

- (BookmarkSpecifics*) build;
- (BookmarkSpecifics*) buildPartial;

- (BookmarkSpecifics_Builder*) mergeFrom:(BookmarkSpecifics*) other;
- (BookmarkSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookmarkSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUrl;
- (NSString*) url;
- (BookmarkSpecifics_Builder*) setUrl:(NSString*) value;
- (BookmarkSpecifics_Builder*) clearUrl;

- (BOOL) hasFavicon;
- (NSData*) favicon;
- (BookmarkSpecifics_Builder*) setFavicon:(NSData*) value;
- (BookmarkSpecifics_Builder*) clearFavicon;

- (BOOL) hasTitle;
- (NSString*) title;
- (BookmarkSpecifics_Builder*) setTitle:(NSString*) value;
- (BookmarkSpecifics_Builder*) clearTitle;
@end

