// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "GetUpdatesCallerInfo.pb.h"

@class DebugEventInfo;
@class DebugEventInfo_Builder;
@class DebugInfo;
@class DebugInfo_Builder;
@class GetUpdatesCallerInfo;
@class GetUpdatesCallerInfo_Builder;
@class SyncCycleCompletedEventInfo;
@class SyncCycleCompletedEventInfo_Builder;
typedef enum {
  DebugEventInfo_EventTypeConnectionStatusChange = 1,
  DebugEventInfo_EventTypeUpdatedToken = 2,
  DebugEventInfo_EventTypePassphraseRequired = 3,
  DebugEventInfo_EventTypePassphraseAccepted = 4,
  DebugEventInfo_EventTypeInitializationComplete = 5,
  DebugEventInfo_EventTypeStopSyncingPermanently = 6,
  DebugEventInfo_EventTypeEncryptedTypesChanged = 9,
  DebugEventInfo_EventTypeEncryptionComplete = 7,
  DebugEventInfo_EventTypeActionableError = 8,
} DebugEventInfo_EventType;

BOOL DebugEventInfo_EventTypeIsValidValue(DebugEventInfo_EventType value);


@interface ClientDebugInfoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface SyncCycleCompletedEventInfo : PBGeneratedMessage {
@private
  BOOL hasNumBlockingConflicts_:1;
  BOOL hasNumNonBlockingConflicts_:1;
  BOOL hasNumEncryptionConflicts_:1;
  BOOL hasNumHierarchyConflicts_:1;
  BOOL hasNumSimpleConflicts_:1;
  BOOL hasNumServerConflicts_:1;
  BOOL hasNumUpdatesDownloaded_:1;
  BOOL hasNumReflectedUpdatesDownloaded_:1;
  BOOL hasCallerInfo_:1;
  int32_t numBlockingConflicts;
  int32_t numNonBlockingConflicts;
  int32_t numEncryptionConflicts;
  int32_t numHierarchyConflicts;
  int32_t numSimpleConflicts;
  int32_t numServerConflicts;
  int32_t numUpdatesDownloaded;
  int32_t numReflectedUpdatesDownloaded;
  GetUpdatesCallerInfo* callerInfo;
}
- (BOOL) hasNumBlockingConflicts;
- (BOOL) hasNumNonBlockingConflicts;
- (BOOL) hasNumEncryptionConflicts;
- (BOOL) hasNumHierarchyConflicts;
- (BOOL) hasNumSimpleConflicts;
- (BOOL) hasNumServerConflicts;
- (BOOL) hasNumUpdatesDownloaded;
- (BOOL) hasNumReflectedUpdatesDownloaded;
- (BOOL) hasCallerInfo;
@property (readonly) int32_t numBlockingConflicts;
@property (readonly) int32_t numNonBlockingConflicts;
@property (readonly) int32_t numEncryptionConflicts;
@property (readonly) int32_t numHierarchyConflicts;
@property (readonly) int32_t numSimpleConflicts;
@property (readonly) int32_t numServerConflicts;
@property (readonly) int32_t numUpdatesDownloaded;
@property (readonly) int32_t numReflectedUpdatesDownloaded;
@property (readonly, retain) GetUpdatesCallerInfo* callerInfo;

+ (SyncCycleCompletedEventInfo*) defaultInstance;
- (SyncCycleCompletedEventInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SyncCycleCompletedEventInfo_Builder*) builder;
+ (SyncCycleCompletedEventInfo_Builder*) builder;
+ (SyncCycleCompletedEventInfo_Builder*) builderWithPrototype:(SyncCycleCompletedEventInfo*) prototype;

+ (SyncCycleCompletedEventInfo*) parseFromData:(NSData*) data;
+ (SyncCycleCompletedEventInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncCycleCompletedEventInfo*) parseFromInputStream:(NSInputStream*) input;
+ (SyncCycleCompletedEventInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncCycleCompletedEventInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SyncCycleCompletedEventInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SyncCycleCompletedEventInfo_Builder : PBGeneratedMessage_Builder {
@private
  SyncCycleCompletedEventInfo* result;
}

- (SyncCycleCompletedEventInfo*) defaultInstance;

- (SyncCycleCompletedEventInfo_Builder*) clear;
- (SyncCycleCompletedEventInfo_Builder*) clone;

- (SyncCycleCompletedEventInfo*) build;
- (SyncCycleCompletedEventInfo*) buildPartial;

- (SyncCycleCompletedEventInfo_Builder*) mergeFrom:(SyncCycleCompletedEventInfo*) other;
- (SyncCycleCompletedEventInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SyncCycleCompletedEventInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNumBlockingConflicts;
- (int32_t) numBlockingConflicts;
- (SyncCycleCompletedEventInfo_Builder*) setNumBlockingConflicts:(int32_t) value;
- (SyncCycleCompletedEventInfo_Builder*) clearNumBlockingConflicts;

- (BOOL) hasNumNonBlockingConflicts;
- (int32_t) numNonBlockingConflicts;
- (SyncCycleCompletedEventInfo_Builder*) setNumNonBlockingConflicts:(int32_t) value;
- (SyncCycleCompletedEventInfo_Builder*) clearNumNonBlockingConflicts;

- (BOOL) hasNumEncryptionConflicts;
- (int32_t) numEncryptionConflicts;
- (SyncCycleCompletedEventInfo_Builder*) setNumEncryptionConflicts:(int32_t) value;
- (SyncCycleCompletedEventInfo_Builder*) clearNumEncryptionConflicts;

- (BOOL) hasNumHierarchyConflicts;
- (int32_t) numHierarchyConflicts;
- (SyncCycleCompletedEventInfo_Builder*) setNumHierarchyConflicts:(int32_t) value;
- (SyncCycleCompletedEventInfo_Builder*) clearNumHierarchyConflicts;

- (BOOL) hasNumSimpleConflicts;
- (int32_t) numSimpleConflicts;
- (SyncCycleCompletedEventInfo_Builder*) setNumSimpleConflicts:(int32_t) value;
- (SyncCycleCompletedEventInfo_Builder*) clearNumSimpleConflicts;

- (BOOL) hasNumServerConflicts;
- (int32_t) numServerConflicts;
- (SyncCycleCompletedEventInfo_Builder*) setNumServerConflicts:(int32_t) value;
- (SyncCycleCompletedEventInfo_Builder*) clearNumServerConflicts;

- (BOOL) hasNumUpdatesDownloaded;
- (int32_t) numUpdatesDownloaded;
- (SyncCycleCompletedEventInfo_Builder*) setNumUpdatesDownloaded:(int32_t) value;
- (SyncCycleCompletedEventInfo_Builder*) clearNumUpdatesDownloaded;

- (BOOL) hasNumReflectedUpdatesDownloaded;
- (int32_t) numReflectedUpdatesDownloaded;
- (SyncCycleCompletedEventInfo_Builder*) setNumReflectedUpdatesDownloaded:(int32_t) value;
- (SyncCycleCompletedEventInfo_Builder*) clearNumReflectedUpdatesDownloaded;

- (BOOL) hasCallerInfo;
- (GetUpdatesCallerInfo*) callerInfo;
- (SyncCycleCompletedEventInfo_Builder*) setCallerInfo:(GetUpdatesCallerInfo*) value;
- (SyncCycleCompletedEventInfo_Builder*) setCallerInfoBuilder:(GetUpdatesCallerInfo_Builder*) builderForValue;
- (SyncCycleCompletedEventInfo_Builder*) mergeCallerInfo:(GetUpdatesCallerInfo*) value;
- (SyncCycleCompletedEventInfo_Builder*) clearCallerInfo;
@end

@interface DebugEventInfo : PBGeneratedMessage {
@private
  BOOL hasSyncCycleCompletedEventInfo_:1;
  BOOL hasType_:1;
  SyncCycleCompletedEventInfo* syncCycleCompletedEventInfo;
  DebugEventInfo_EventType type;
}
- (BOOL) hasType;
- (BOOL) hasSyncCycleCompletedEventInfo;
@property (readonly) DebugEventInfo_EventType type;
@property (readonly, retain) SyncCycleCompletedEventInfo* syncCycleCompletedEventInfo;

+ (DebugEventInfo*) defaultInstance;
- (DebugEventInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DebugEventInfo_Builder*) builder;
+ (DebugEventInfo_Builder*) builder;
+ (DebugEventInfo_Builder*) builderWithPrototype:(DebugEventInfo*) prototype;

+ (DebugEventInfo*) parseFromData:(NSData*) data;
+ (DebugEventInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DebugEventInfo*) parseFromInputStream:(NSInputStream*) input;
+ (DebugEventInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DebugEventInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DebugEventInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DebugEventInfo_Builder : PBGeneratedMessage_Builder {
@private
  DebugEventInfo* result;
}

- (DebugEventInfo*) defaultInstance;

- (DebugEventInfo_Builder*) clear;
- (DebugEventInfo_Builder*) clone;

- (DebugEventInfo*) build;
- (DebugEventInfo*) buildPartial;

- (DebugEventInfo_Builder*) mergeFrom:(DebugEventInfo*) other;
- (DebugEventInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DebugEventInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (DebugEventInfo_EventType) type;
- (DebugEventInfo_Builder*) setType:(DebugEventInfo_EventType) value;
- (DebugEventInfo_Builder*) clearType;

- (BOOL) hasSyncCycleCompletedEventInfo;
- (SyncCycleCompletedEventInfo*) syncCycleCompletedEventInfo;
- (DebugEventInfo_Builder*) setSyncCycleCompletedEventInfo:(SyncCycleCompletedEventInfo*) value;
- (DebugEventInfo_Builder*) setSyncCycleCompletedEventInfoBuilder:(SyncCycleCompletedEventInfo_Builder*) builderForValue;
- (DebugEventInfo_Builder*) mergeSyncCycleCompletedEventInfo:(SyncCycleCompletedEventInfo*) value;
- (DebugEventInfo_Builder*) clearSyncCycleCompletedEventInfo;
@end

@interface DebugInfo : PBGeneratedMessage {
@private
  BOOL hasCryptographerReady_:1;
  BOOL hasCryptographerHasPendingKeys_:1;
  BOOL hasEventsDropped_:1;
  BOOL cryptographerReady_:1;
  BOOL cryptographerHasPendingKeys_:1;
  BOOL eventsDropped_:1;
  NSMutableArray* mutableEventsList;
}
- (BOOL) hasCryptographerReady;
- (BOOL) hasCryptographerHasPendingKeys;
- (BOOL) hasEventsDropped;
- (BOOL) cryptographerReady;
- (BOOL) cryptographerHasPendingKeys;
- (BOOL) eventsDropped;
- (NSArray*) eventsList;
- (DebugEventInfo*) eventsAtIndex:(int32_t) index;

+ (DebugInfo*) defaultInstance;
- (DebugInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DebugInfo_Builder*) builder;
+ (DebugInfo_Builder*) builder;
+ (DebugInfo_Builder*) builderWithPrototype:(DebugInfo*) prototype;

+ (DebugInfo*) parseFromData:(NSData*) data;
+ (DebugInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DebugInfo*) parseFromInputStream:(NSInputStream*) input;
+ (DebugInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DebugInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DebugInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DebugInfo_Builder : PBGeneratedMessage_Builder {
@private
  DebugInfo* result;
}

- (DebugInfo*) defaultInstance;

- (DebugInfo_Builder*) clear;
- (DebugInfo_Builder*) clone;

- (DebugInfo*) build;
- (DebugInfo*) buildPartial;

- (DebugInfo_Builder*) mergeFrom:(DebugInfo*) other;
- (DebugInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DebugInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) eventsList;
- (DebugEventInfo*) eventsAtIndex:(int32_t) index;
- (DebugInfo_Builder*) replaceEventsAtIndex:(int32_t) index with:(DebugEventInfo*) value;
- (DebugInfo_Builder*) addEvents:(DebugEventInfo*) value;
- (DebugInfo_Builder*) addAllEvents:(NSArray*) values;
- (DebugInfo_Builder*) clearEventsList;

- (BOOL) hasCryptographerReady;
- (BOOL) cryptographerReady;
- (DebugInfo_Builder*) setCryptographerReady:(BOOL) value;
- (DebugInfo_Builder*) clearCryptographerReady;

- (BOOL) hasCryptographerHasPendingKeys;
- (BOOL) cryptographerHasPendingKeys;
- (DebugInfo_Builder*) setCryptographerHasPendingKeys:(BOOL) value;
- (DebugInfo_Builder*) clearCryptographerHasPendingKeys;

- (BOOL) hasEventsDropped;
- (BOOL) eventsDropped;
- (DebugInfo_Builder*) setEventsDropped:(BOOL) value;
- (DebugInfo_Builder*) clearEventsDropped;
@end

