// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ExtensionSettingSpecifics;
@class ExtensionSettingSpecifics_Builder;

@interface ExtensionSettingSpecificsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ExtensionSettingSpecifics : PBGeneratedMessage {
@private
  BOOL hasExtensionId_:1;
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  NSString* extensionId;
  NSString* key;
  NSString* value;
}
- (BOOL) hasExtensionId;
- (BOOL) hasKey;
- (BOOL) hasValue;
@property (readonly, retain) NSString* extensionId;
@property (readonly, retain) NSString* key;
@property (readonly, retain) NSString* value;

+ (ExtensionSettingSpecifics*) defaultInstance;
- (ExtensionSettingSpecifics*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ExtensionSettingSpecifics_Builder*) builder;
+ (ExtensionSettingSpecifics_Builder*) builder;
+ (ExtensionSettingSpecifics_Builder*) builderWithPrototype:(ExtensionSettingSpecifics*) prototype;

+ (ExtensionSettingSpecifics*) parseFromData:(NSData*) data;
+ (ExtensionSettingSpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ExtensionSettingSpecifics*) parseFromInputStream:(NSInputStream*) input;
+ (ExtensionSettingSpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ExtensionSettingSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ExtensionSettingSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ExtensionSettingSpecifics_Builder : PBGeneratedMessage_Builder {
@private
  ExtensionSettingSpecifics* result;
}

- (ExtensionSettingSpecifics*) defaultInstance;

- (ExtensionSettingSpecifics_Builder*) clear;
- (ExtensionSettingSpecifics_Builder*) clone;

- (ExtensionSettingSpecifics*) build;
- (ExtensionSettingSpecifics*) buildPartial;

- (ExtensionSettingSpecifics_Builder*) mergeFrom:(ExtensionSettingSpecifics*) other;
- (ExtensionSettingSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ExtensionSettingSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasExtensionId;
- (NSString*) extensionId;
- (ExtensionSettingSpecifics_Builder*) setExtensionId:(NSString*) value;
- (ExtensionSettingSpecifics_Builder*) clearExtensionId;

- (BOOL) hasKey;
- (NSString*) key;
- (ExtensionSettingSpecifics_Builder*) setKey:(NSString*) value;
- (ExtensionSettingSpecifics_Builder*) clearKey;

- (BOOL) hasValue;
- (NSString*) value;
- (ExtensionSettingSpecifics_Builder*) setValue:(NSString*) value;
- (ExtensionSettingSpecifics_Builder*) clearValue;
@end

