// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class GetUpdatesCallerInfo;
@class GetUpdatesCallerInfo_Builder;
typedef enum {
  GetUpdatesCallerInfo_GetUpdatesSourceUnknown = 0,
  GetUpdatesCallerInfo_GetUpdatesSourceFirstUpdate = 1,
  GetUpdatesCallerInfo_GetUpdatesSourceLocal = 2,
  GetUpdatesCallerInfo_GetUpdatesSourceNotification = 3,
  GetUpdatesCallerInfo_GetUpdatesSourcePeriodic = 4,
  GetUpdatesCallerInfo_GetUpdatesSourceSyncCycleContinuation = 5,
  GetUpdatesCallerInfo_GetUpdatesSourceClearPrivateData = 6,
  GetUpdatesCallerInfo_GetUpdatesSourceNewlySupportedDatatype = 7,
  GetUpdatesCallerInfo_GetUpdatesSourceMigration = 8,
  GetUpdatesCallerInfo_GetUpdatesSourceNewClient = 9,
  GetUpdatesCallerInfo_GetUpdatesSourceReconfiguration = 10,
  GetUpdatesCallerInfo_GetUpdatesSourceDatatypeRefresh = 11,
} GetUpdatesCallerInfo_GetUpdatesSource;

BOOL GetUpdatesCallerInfo_GetUpdatesSourceIsValidValue(GetUpdatesCallerInfo_GetUpdatesSource value);


@interface GetUpdatesCallerInfoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GetUpdatesCallerInfo : PBGeneratedMessage {
@private
  BOOL hasNotificationsEnabled_:1;
  BOOL hasSource_:1;
  BOOL notificationsEnabled_:1;
  GetUpdatesCallerInfo_GetUpdatesSource source;
}
- (BOOL) hasSource;
- (BOOL) hasNotificationsEnabled;
@property (readonly) GetUpdatesCallerInfo_GetUpdatesSource source;
- (BOOL) notificationsEnabled;

+ (GetUpdatesCallerInfo*) defaultInstance;
- (GetUpdatesCallerInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetUpdatesCallerInfo_Builder*) builder;
+ (GetUpdatesCallerInfo_Builder*) builder;
+ (GetUpdatesCallerInfo_Builder*) builderWithPrototype:(GetUpdatesCallerInfo*) prototype;

+ (GetUpdatesCallerInfo*) parseFromData:(NSData*) data;
+ (GetUpdatesCallerInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesCallerInfo*) parseFromInputStream:(NSInputStream*) input;
+ (GetUpdatesCallerInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesCallerInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetUpdatesCallerInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetUpdatesCallerInfo_Builder : PBGeneratedMessage_Builder {
@private
  GetUpdatesCallerInfo* result;
}

- (GetUpdatesCallerInfo*) defaultInstance;

- (GetUpdatesCallerInfo_Builder*) clear;
- (GetUpdatesCallerInfo_Builder*) clone;

- (GetUpdatesCallerInfo*) build;
- (GetUpdatesCallerInfo*) buildPartial;

- (GetUpdatesCallerInfo_Builder*) mergeFrom:(GetUpdatesCallerInfo*) other;
- (GetUpdatesCallerInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetUpdatesCallerInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSource;
- (GetUpdatesCallerInfo_GetUpdatesSource) source;
- (GetUpdatesCallerInfo_Builder*) setSource:(GetUpdatesCallerInfo_GetUpdatesSource) value;
- (GetUpdatesCallerInfo_Builder*) clearSource;

- (BOOL) hasNotificationsEnabled;
- (BOOL) notificationsEnabled;
- (GetUpdatesCallerInfo_Builder*) setNotificationsEnabled:(BOOL) value;
- (GetUpdatesCallerInfo_Builder*) clearNotificationsEnabled;
@end

