// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "PreferenceSpecifics.pb.h"

@implementation PreferenceSpecificsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PreferenceSpecificsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PreferenceSpecifics ()
@property (retain) NSString* name;
@property (retain) NSString* value;
@end

@implementation PreferenceSpecifics

- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (BOOL) hasValue {
  return !!hasValue_;
}
- (void) setHasValue:(BOOL) value {
  hasValue_ = !!value;
}
@synthesize value;
- (void) dealloc {
  self.name = nil;
  self.value = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.name = @"";
    self.value = @"";
  }
  return self;
}
static PreferenceSpecifics* defaultPreferenceSpecificsInstance = nil;
+ (void) initialize {
  if (self == [PreferenceSpecifics class]) {
    defaultPreferenceSpecificsInstance = [[PreferenceSpecifics alloc] init];
  }
}
+ (PreferenceSpecifics*) defaultInstance {
  return defaultPreferenceSpecificsInstance;
}
- (PreferenceSpecifics*) defaultInstance {
  return defaultPreferenceSpecificsInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasName) {
    [output writeString:1 value:self.name];
  }
  if (self.hasValue) {
    [output writeString:2 value:self.value];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasName) {
    size += computeStringSize(1, self.name);
  }
  if (self.hasValue) {
    size += computeStringSize(2, self.value);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (PreferenceSpecifics*) parseFromData:(NSData*) data {
  return (PreferenceSpecifics*)[[[PreferenceSpecifics builder] mergeFromData:data] build];
}
+ (PreferenceSpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PreferenceSpecifics*)[[[PreferenceSpecifics builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PreferenceSpecifics*) parseFromInputStream:(NSInputStream*) input {
  return (PreferenceSpecifics*)[[[PreferenceSpecifics builder] mergeFromInputStream:input] build];
}
+ (PreferenceSpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PreferenceSpecifics*)[[[PreferenceSpecifics builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PreferenceSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PreferenceSpecifics*)[[[PreferenceSpecifics builder] mergeFromCodedInputStream:input] build];
}
+ (PreferenceSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PreferenceSpecifics*)[[[PreferenceSpecifics builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PreferenceSpecifics_Builder*) builder {
  return [[[PreferenceSpecifics_Builder alloc] init] autorelease];
}
+ (PreferenceSpecifics_Builder*) builderWithPrototype:(PreferenceSpecifics*) prototype {
  return [[PreferenceSpecifics builder] mergeFrom:prototype];
}
- (PreferenceSpecifics_Builder*) builder {
  return [PreferenceSpecifics builder];
}
@end

@interface PreferenceSpecifics_Builder()
@property (retain) PreferenceSpecifics* result;
@end

@implementation PreferenceSpecifics_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PreferenceSpecifics alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PreferenceSpecifics_Builder*) clear {
  self.result = [[[PreferenceSpecifics alloc] init] autorelease];
  return self;
}
- (PreferenceSpecifics_Builder*) clone {
  return [PreferenceSpecifics builderWithPrototype:result];
}
- (PreferenceSpecifics*) defaultInstance {
  return [PreferenceSpecifics defaultInstance];
}
- (PreferenceSpecifics*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PreferenceSpecifics*) buildPartial {
  PreferenceSpecifics* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PreferenceSpecifics_Builder*) mergeFrom:(PreferenceSpecifics*) other {
  if (other == [PreferenceSpecifics defaultInstance]) {
    return self;
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasValue) {
    [self setValue:other.value];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PreferenceSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PreferenceSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setName:[input readString]];
        break;
      }
      case 18: {
        [self setValue:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (PreferenceSpecifics_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (PreferenceSpecifics_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasValue {
  return result.hasValue;
}
- (NSString*) value {
  return result.value;
}
- (PreferenceSpecifics_Builder*) setValue:(NSString*) value {
  result.hasValue = YES;
  result.value = value;
  return self;
}
- (PreferenceSpecifics_Builder*) clearValue {
  result.hasValue = NO;
  result.value = @"";
  return self;
}
@end

