// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class SearchEngineSpecifics;
@class SearchEngineSpecifics_Builder;

@interface SearchEngineSpecificsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface SearchEngineSpecifics : PBGeneratedMessage {
@private
  BOOL hasSafeForAutoreplace_:1;
  BOOL hasShowInDefaultList_:1;
  BOOL hasAutogenerateKeyword_:1;
  BOOL hasDateCreated_:1;
  BOOL hasLastModified_:1;
  BOOL hasPrepopulateId_:1;
  BOOL hasShortName_:1;
  BOOL hasKeyword_:1;
  BOOL hasFaviconUrl_:1;
  BOOL hasUrl_:1;
  BOOL hasOriginatingUrl_:1;
  BOOL hasInputEncodings_:1;
  BOOL hasSuggestionsUrl_:1;
  BOOL hasInstantUrl_:1;
  BOOL hasSyncGuid_:1;
  BOOL safeForAutoreplace_:1;
  BOOL showInDefaultList_:1;
  BOOL autogenerateKeyword_:1;
  int64_t dateCreated;
  int64_t lastModified;
  int32_t prepopulateId;
  NSString* shortName;
  NSString* keyword;
  NSString* faviconUrl;
  NSString* url;
  NSString* originatingUrl;
  NSString* inputEncodings;
  NSString* suggestionsUrl;
  NSString* instantUrl;
  NSString* syncGuid;
}
- (BOOL) hasShortName;
- (BOOL) hasKeyword;
- (BOOL) hasFaviconUrl;
- (BOOL) hasUrl;
- (BOOL) hasSafeForAutoreplace;
- (BOOL) hasOriginatingUrl;
- (BOOL) hasDateCreated;
- (BOOL) hasInputEncodings;
- (BOOL) hasShowInDefaultList;
- (BOOL) hasSuggestionsUrl;
- (BOOL) hasPrepopulateId;
- (BOOL) hasAutogenerateKeyword;
- (BOOL) hasInstantUrl;
- (BOOL) hasLastModified;
- (BOOL) hasSyncGuid;
@property (readonly, retain) NSString* shortName;
@property (readonly, retain) NSString* keyword;
@property (readonly, retain) NSString* faviconUrl;
@property (readonly, retain) NSString* url;
- (BOOL) safeForAutoreplace;
@property (readonly, retain) NSString* originatingUrl;
@property (readonly) int64_t dateCreated;
@property (readonly, retain) NSString* inputEncodings;
- (BOOL) showInDefaultList;
@property (readonly, retain) NSString* suggestionsUrl;
@property (readonly) int32_t prepopulateId;
- (BOOL) autogenerateKeyword;
@property (readonly, retain) NSString* instantUrl;
@property (readonly) int64_t lastModified;
@property (readonly, retain) NSString* syncGuid;

+ (SearchEngineSpecifics*) defaultInstance;
- (SearchEngineSpecifics*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SearchEngineSpecifics_Builder*) builder;
+ (SearchEngineSpecifics_Builder*) builder;
+ (SearchEngineSpecifics_Builder*) builderWithPrototype:(SearchEngineSpecifics*) prototype;

+ (SearchEngineSpecifics*) parseFromData:(NSData*) data;
+ (SearchEngineSpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SearchEngineSpecifics*) parseFromInputStream:(NSInputStream*) input;
+ (SearchEngineSpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SearchEngineSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SearchEngineSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SearchEngineSpecifics_Builder : PBGeneratedMessage_Builder {
@private
  SearchEngineSpecifics* result;
}

- (SearchEngineSpecifics*) defaultInstance;

- (SearchEngineSpecifics_Builder*) clear;
- (SearchEngineSpecifics_Builder*) clone;

- (SearchEngineSpecifics*) build;
- (SearchEngineSpecifics*) buildPartial;

- (SearchEngineSpecifics_Builder*) mergeFrom:(SearchEngineSpecifics*) other;
- (SearchEngineSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SearchEngineSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasShortName;
- (NSString*) shortName;
- (SearchEngineSpecifics_Builder*) setShortName:(NSString*) value;
- (SearchEngineSpecifics_Builder*) clearShortName;

- (BOOL) hasKeyword;
- (NSString*) keyword;
- (SearchEngineSpecifics_Builder*) setKeyword:(NSString*) value;
- (SearchEngineSpecifics_Builder*) clearKeyword;

- (BOOL) hasFaviconUrl;
- (NSString*) faviconUrl;
- (SearchEngineSpecifics_Builder*) setFaviconUrl:(NSString*) value;
- (SearchEngineSpecifics_Builder*) clearFaviconUrl;

- (BOOL) hasUrl;
- (NSString*) url;
- (SearchEngineSpecifics_Builder*) setUrl:(NSString*) value;
- (SearchEngineSpecifics_Builder*) clearUrl;

- (BOOL) hasSafeForAutoreplace;
- (BOOL) safeForAutoreplace;
- (SearchEngineSpecifics_Builder*) setSafeForAutoreplace:(BOOL) value;
- (SearchEngineSpecifics_Builder*) clearSafeForAutoreplace;

- (BOOL) hasOriginatingUrl;
- (NSString*) originatingUrl;
- (SearchEngineSpecifics_Builder*) setOriginatingUrl:(NSString*) value;
- (SearchEngineSpecifics_Builder*) clearOriginatingUrl;

- (BOOL) hasDateCreated;
- (int64_t) dateCreated;
- (SearchEngineSpecifics_Builder*) setDateCreated:(int64_t) value;
- (SearchEngineSpecifics_Builder*) clearDateCreated;

- (BOOL) hasInputEncodings;
- (NSString*) inputEncodings;
- (SearchEngineSpecifics_Builder*) setInputEncodings:(NSString*) value;
- (SearchEngineSpecifics_Builder*) clearInputEncodings;

- (BOOL) hasShowInDefaultList;
- (BOOL) showInDefaultList;
- (SearchEngineSpecifics_Builder*) setShowInDefaultList:(BOOL) value;
- (SearchEngineSpecifics_Builder*) clearShowInDefaultList;

- (BOOL) hasSuggestionsUrl;
- (NSString*) suggestionsUrl;
- (SearchEngineSpecifics_Builder*) setSuggestionsUrl:(NSString*) value;
- (SearchEngineSpecifics_Builder*) clearSuggestionsUrl;

- (BOOL) hasPrepopulateId;
- (int32_t) prepopulateId;
- (SearchEngineSpecifics_Builder*) setPrepopulateId:(int32_t) value;
- (SearchEngineSpecifics_Builder*) clearPrepopulateId;

- (BOOL) hasAutogenerateKeyword;
- (BOOL) autogenerateKeyword;
- (SearchEngineSpecifics_Builder*) setAutogenerateKeyword:(BOOL) value;
- (SearchEngineSpecifics_Builder*) clearAutogenerateKeyword;

- (BOOL) hasInstantUrl;
- (NSString*) instantUrl;
- (SearchEngineSpecifics_Builder*) setInstantUrl:(NSString*) value;
- (SearchEngineSpecifics_Builder*) clearInstantUrl;

- (BOOL) hasLastModified;
- (int64_t) lastModified;
- (SearchEngineSpecifics_Builder*) setLastModified:(int64_t) value;
- (SearchEngineSpecifics_Builder*) clearLastModified;

- (BOOL) hasSyncGuid;
- (NSString*) syncGuid;
- (SearchEngineSpecifics_Builder*) setSyncGuid:(NSString*) value;
- (SearchEngineSpecifics_Builder*) clearSyncGuid;
@end

