// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "SearchEngineSpecifics.pb.h"

@implementation SearchEngineSpecificsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [SearchEngineSpecificsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface SearchEngineSpecifics ()
@property (retain) NSString* shortName;
@property (retain) NSString* keyword;
@property (retain) NSString* faviconUrl;
@property (retain) NSString* url;
@property BOOL safeForAutoreplace;
@property (retain) NSString* originatingUrl;
@property int64_t dateCreated;
@property (retain) NSString* inputEncodings;
@property BOOL showInDefaultList;
@property (retain) NSString* suggestionsUrl;
@property int32_t prepopulateId;
@property BOOL autogenerateKeyword;
@property (retain) NSString* instantUrl;
@property int64_t lastModified;
@property (retain) NSString* syncGuid;
@end

@implementation SearchEngineSpecifics

- (BOOL) hasShortName {
  return !!hasShortName_;
}
- (void) setHasShortName:(BOOL) value {
  hasShortName_ = !!value;
}
@synthesize shortName;
- (BOOL) hasKeyword {
  return !!hasKeyword_;
}
- (void) setHasKeyword:(BOOL) value {
  hasKeyword_ = !!value;
}
@synthesize keyword;
- (BOOL) hasFaviconUrl {
  return !!hasFaviconUrl_;
}
- (void) setHasFaviconUrl:(BOOL) value {
  hasFaviconUrl_ = !!value;
}
@synthesize faviconUrl;
- (BOOL) hasUrl {
  return !!hasUrl_;
}
- (void) setHasUrl:(BOOL) value {
  hasUrl_ = !!value;
}
@synthesize url;
- (BOOL) hasSafeForAutoreplace {
  return !!hasSafeForAutoreplace_;
}
- (void) setHasSafeForAutoreplace:(BOOL) value {
  hasSafeForAutoreplace_ = !!value;
}
- (BOOL) safeForAutoreplace {
  return !!safeForAutoreplace_;
}
- (void) setSafeForAutoreplace:(BOOL) value {
  safeForAutoreplace_ = !!value;
}
- (BOOL) hasOriginatingUrl {
  return !!hasOriginatingUrl_;
}
- (void) setHasOriginatingUrl:(BOOL) value {
  hasOriginatingUrl_ = !!value;
}
@synthesize originatingUrl;
- (BOOL) hasDateCreated {
  return !!hasDateCreated_;
}
- (void) setHasDateCreated:(BOOL) value {
  hasDateCreated_ = !!value;
}
@synthesize dateCreated;
- (BOOL) hasInputEncodings {
  return !!hasInputEncodings_;
}
- (void) setHasInputEncodings:(BOOL) value {
  hasInputEncodings_ = !!value;
}
@synthesize inputEncodings;
- (BOOL) hasShowInDefaultList {
  return !!hasShowInDefaultList_;
}
- (void) setHasShowInDefaultList:(BOOL) value {
  hasShowInDefaultList_ = !!value;
}
- (BOOL) showInDefaultList {
  return !!showInDefaultList_;
}
- (void) setShowInDefaultList:(BOOL) value {
  showInDefaultList_ = !!value;
}
- (BOOL) hasSuggestionsUrl {
  return !!hasSuggestionsUrl_;
}
- (void) setHasSuggestionsUrl:(BOOL) value {
  hasSuggestionsUrl_ = !!value;
}
@synthesize suggestionsUrl;
- (BOOL) hasPrepopulateId {
  return !!hasPrepopulateId_;
}
- (void) setHasPrepopulateId:(BOOL) value {
  hasPrepopulateId_ = !!value;
}
@synthesize prepopulateId;
- (BOOL) hasAutogenerateKeyword {
  return !!hasAutogenerateKeyword_;
}
- (void) setHasAutogenerateKeyword:(BOOL) value {
  hasAutogenerateKeyword_ = !!value;
}
- (BOOL) autogenerateKeyword {
  return !!autogenerateKeyword_;
}
- (void) setAutogenerateKeyword:(BOOL) value {
  autogenerateKeyword_ = !!value;
}
- (BOOL) hasInstantUrl {
  return !!hasInstantUrl_;
}
- (void) setHasInstantUrl:(BOOL) value {
  hasInstantUrl_ = !!value;
}
@synthesize instantUrl;
- (BOOL) hasLastModified {
  return !!hasLastModified_;
}
- (void) setHasLastModified:(BOOL) value {
  hasLastModified_ = !!value;
}
@synthesize lastModified;
- (BOOL) hasSyncGuid {
  return !!hasSyncGuid_;
}
- (void) setHasSyncGuid:(BOOL) value {
  hasSyncGuid_ = !!value;
}
@synthesize syncGuid;
- (void) dealloc {
  self.shortName = nil;
  self.keyword = nil;
  self.faviconUrl = nil;
  self.url = nil;
  self.originatingUrl = nil;
  self.inputEncodings = nil;
  self.suggestionsUrl = nil;
  self.instantUrl = nil;
  self.syncGuid = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.shortName = @"";
    self.keyword = @"";
    self.faviconUrl = @"";
    self.url = @"";
    self.safeForAutoreplace = NO;
    self.originatingUrl = @"";
    self.dateCreated = 0L;
    self.inputEncodings = @"";
    self.showInDefaultList = NO;
    self.suggestionsUrl = @"";
    self.prepopulateId = 0;
    self.autogenerateKeyword = NO;
    self.instantUrl = @"";
    self.lastModified = 0L;
    self.syncGuid = @"";
  }
  return self;
}
static SearchEngineSpecifics* defaultSearchEngineSpecificsInstance = nil;
+ (void) initialize {
  if (self == [SearchEngineSpecifics class]) {
    defaultSearchEngineSpecificsInstance = [[SearchEngineSpecifics alloc] init];
  }
}
+ (SearchEngineSpecifics*) defaultInstance {
  return defaultSearchEngineSpecificsInstance;
}
- (SearchEngineSpecifics*) defaultInstance {
  return defaultSearchEngineSpecificsInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasShortName) {
    [output writeString:1 value:self.shortName];
  }
  if (self.hasKeyword) {
    [output writeString:2 value:self.keyword];
  }
  if (self.hasFaviconUrl) {
    [output writeString:3 value:self.faviconUrl];
  }
  if (self.hasUrl) {
    [output writeString:4 value:self.url];
  }
  if (self.hasSafeForAutoreplace) {
    [output writeBool:5 value:self.safeForAutoreplace];
  }
  if (self.hasOriginatingUrl) {
    [output writeString:6 value:self.originatingUrl];
  }
  if (self.hasDateCreated) {
    [output writeInt64:7 value:self.dateCreated];
  }
  if (self.hasInputEncodings) {
    [output writeString:8 value:self.inputEncodings];
  }
  if (self.hasShowInDefaultList) {
    [output writeBool:9 value:self.showInDefaultList];
  }
  if (self.hasSuggestionsUrl) {
    [output writeString:10 value:self.suggestionsUrl];
  }
  if (self.hasPrepopulateId) {
    [output writeInt32:11 value:self.prepopulateId];
  }
  if (self.hasAutogenerateKeyword) {
    [output writeBool:12 value:self.autogenerateKeyword];
  }
  if (self.hasInstantUrl) {
    [output writeString:15 value:self.instantUrl];
  }
  if (self.hasLastModified) {
    [output writeInt64:17 value:self.lastModified];
  }
  if (self.hasSyncGuid) {
    [output writeString:18 value:self.syncGuid];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasShortName) {
    size += computeStringSize(1, self.shortName);
  }
  if (self.hasKeyword) {
    size += computeStringSize(2, self.keyword);
  }
  if (self.hasFaviconUrl) {
    size += computeStringSize(3, self.faviconUrl);
  }
  if (self.hasUrl) {
    size += computeStringSize(4, self.url);
  }
  if (self.hasSafeForAutoreplace) {
    size += computeBoolSize(5, self.safeForAutoreplace);
  }
  if (self.hasOriginatingUrl) {
    size += computeStringSize(6, self.originatingUrl);
  }
  if (self.hasDateCreated) {
    size += computeInt64Size(7, self.dateCreated);
  }
  if (self.hasInputEncodings) {
    size += computeStringSize(8, self.inputEncodings);
  }
  if (self.hasShowInDefaultList) {
    size += computeBoolSize(9, self.showInDefaultList);
  }
  if (self.hasSuggestionsUrl) {
    size += computeStringSize(10, self.suggestionsUrl);
  }
  if (self.hasPrepopulateId) {
    size += computeInt32Size(11, self.prepopulateId);
  }
  if (self.hasAutogenerateKeyword) {
    size += computeBoolSize(12, self.autogenerateKeyword);
  }
  if (self.hasInstantUrl) {
    size += computeStringSize(15, self.instantUrl);
  }
  if (self.hasLastModified) {
    size += computeInt64Size(17, self.lastModified);
  }
  if (self.hasSyncGuid) {
    size += computeStringSize(18, self.syncGuid);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (SearchEngineSpecifics*) parseFromData:(NSData*) data {
  return (SearchEngineSpecifics*)[[[SearchEngineSpecifics builder] mergeFromData:data] build];
}
+ (SearchEngineSpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SearchEngineSpecifics*)[[[SearchEngineSpecifics builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SearchEngineSpecifics*) parseFromInputStream:(NSInputStream*) input {
  return (SearchEngineSpecifics*)[[[SearchEngineSpecifics builder] mergeFromInputStream:input] build];
}
+ (SearchEngineSpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SearchEngineSpecifics*)[[[SearchEngineSpecifics builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SearchEngineSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SearchEngineSpecifics*)[[[SearchEngineSpecifics builder] mergeFromCodedInputStream:input] build];
}
+ (SearchEngineSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SearchEngineSpecifics*)[[[SearchEngineSpecifics builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SearchEngineSpecifics_Builder*) builder {
  return [[[SearchEngineSpecifics_Builder alloc] init] autorelease];
}
+ (SearchEngineSpecifics_Builder*) builderWithPrototype:(SearchEngineSpecifics*) prototype {
  return [[SearchEngineSpecifics builder] mergeFrom:prototype];
}
- (SearchEngineSpecifics_Builder*) builder {
  return [SearchEngineSpecifics builder];
}
@end

@interface SearchEngineSpecifics_Builder()
@property (retain) SearchEngineSpecifics* result;
@end

@implementation SearchEngineSpecifics_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[SearchEngineSpecifics alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (SearchEngineSpecifics_Builder*) clear {
  self.result = [[[SearchEngineSpecifics alloc] init] autorelease];
  return self;
}
- (SearchEngineSpecifics_Builder*) clone {
  return [SearchEngineSpecifics builderWithPrototype:result];
}
- (SearchEngineSpecifics*) defaultInstance {
  return [SearchEngineSpecifics defaultInstance];
}
- (SearchEngineSpecifics*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SearchEngineSpecifics*) buildPartial {
  SearchEngineSpecifics* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (SearchEngineSpecifics_Builder*) mergeFrom:(SearchEngineSpecifics*) other {
  if (other == [SearchEngineSpecifics defaultInstance]) {
    return self;
  }
  if (other.hasShortName) {
    [self setShortName:other.shortName];
  }
  if (other.hasKeyword) {
    [self setKeyword:other.keyword];
  }
  if (other.hasFaviconUrl) {
    [self setFaviconUrl:other.faviconUrl];
  }
  if (other.hasUrl) {
    [self setUrl:other.url];
  }
  if (other.hasSafeForAutoreplace) {
    [self setSafeForAutoreplace:other.safeForAutoreplace];
  }
  if (other.hasOriginatingUrl) {
    [self setOriginatingUrl:other.originatingUrl];
  }
  if (other.hasDateCreated) {
    [self setDateCreated:other.dateCreated];
  }
  if (other.hasInputEncodings) {
    [self setInputEncodings:other.inputEncodings];
  }
  if (other.hasShowInDefaultList) {
    [self setShowInDefaultList:other.showInDefaultList];
  }
  if (other.hasSuggestionsUrl) {
    [self setSuggestionsUrl:other.suggestionsUrl];
  }
  if (other.hasPrepopulateId) {
    [self setPrepopulateId:other.prepopulateId];
  }
  if (other.hasAutogenerateKeyword) {
    [self setAutogenerateKeyword:other.autogenerateKeyword];
  }
  if (other.hasInstantUrl) {
    [self setInstantUrl:other.instantUrl];
  }
  if (other.hasLastModified) {
    [self setLastModified:other.lastModified];
  }
  if (other.hasSyncGuid) {
    [self setSyncGuid:other.syncGuid];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SearchEngineSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SearchEngineSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setShortName:[input readString]];
        break;
      }
      case 18: {
        [self setKeyword:[input readString]];
        break;
      }
      case 26: {
        [self setFaviconUrl:[input readString]];
        break;
      }
      case 34: {
        [self setUrl:[input readString]];
        break;
      }
      case 40: {
        [self setSafeForAutoreplace:[input readBool]];
        break;
      }
      case 50: {
        [self setOriginatingUrl:[input readString]];
        break;
      }
      case 56: {
        [self setDateCreated:[input readInt64]];
        break;
      }
      case 66: {
        [self setInputEncodings:[input readString]];
        break;
      }
      case 72: {
        [self setShowInDefaultList:[input readBool]];
        break;
      }
      case 82: {
        [self setSuggestionsUrl:[input readString]];
        break;
      }
      case 88: {
        [self setPrepopulateId:[input readInt32]];
        break;
      }
      case 96: {
        [self setAutogenerateKeyword:[input readBool]];
        break;
      }
      case 122: {
        [self setInstantUrl:[input readString]];
        break;
      }
      case 136: {
        [self setLastModified:[input readInt64]];
        break;
      }
      case 146: {
        [self setSyncGuid:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasShortName {
  return result.hasShortName;
}
- (NSString*) shortName {
  return result.shortName;
}
- (SearchEngineSpecifics_Builder*) setShortName:(NSString*) value {
  result.hasShortName = YES;
  result.shortName = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearShortName {
  result.hasShortName = NO;
  result.shortName = @"";
  return self;
}
- (BOOL) hasKeyword {
  return result.hasKeyword;
}
- (NSString*) keyword {
  return result.keyword;
}
- (SearchEngineSpecifics_Builder*) setKeyword:(NSString*) value {
  result.hasKeyword = YES;
  result.keyword = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearKeyword {
  result.hasKeyword = NO;
  result.keyword = @"";
  return self;
}
- (BOOL) hasFaviconUrl {
  return result.hasFaviconUrl;
}
- (NSString*) faviconUrl {
  return result.faviconUrl;
}
- (SearchEngineSpecifics_Builder*) setFaviconUrl:(NSString*) value {
  result.hasFaviconUrl = YES;
  result.faviconUrl = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearFaviconUrl {
  result.hasFaviconUrl = NO;
  result.faviconUrl = @"";
  return self;
}
- (BOOL) hasUrl {
  return result.hasUrl;
}
- (NSString*) url {
  return result.url;
}
- (SearchEngineSpecifics_Builder*) setUrl:(NSString*) value {
  result.hasUrl = YES;
  result.url = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearUrl {
  result.hasUrl = NO;
  result.url = @"";
  return self;
}
- (BOOL) hasSafeForAutoreplace {
  return result.hasSafeForAutoreplace;
}
- (BOOL) safeForAutoreplace {
  return result.safeForAutoreplace;
}
- (SearchEngineSpecifics_Builder*) setSafeForAutoreplace:(BOOL) value {
  result.hasSafeForAutoreplace = YES;
  result.safeForAutoreplace = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearSafeForAutoreplace {
  result.hasSafeForAutoreplace = NO;
  result.safeForAutoreplace = NO;
  return self;
}
- (BOOL) hasOriginatingUrl {
  return result.hasOriginatingUrl;
}
- (NSString*) originatingUrl {
  return result.originatingUrl;
}
- (SearchEngineSpecifics_Builder*) setOriginatingUrl:(NSString*) value {
  result.hasOriginatingUrl = YES;
  result.originatingUrl = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearOriginatingUrl {
  result.hasOriginatingUrl = NO;
  result.originatingUrl = @"";
  return self;
}
- (BOOL) hasDateCreated {
  return result.hasDateCreated;
}
- (int64_t) dateCreated {
  return result.dateCreated;
}
- (SearchEngineSpecifics_Builder*) setDateCreated:(int64_t) value {
  result.hasDateCreated = YES;
  result.dateCreated = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearDateCreated {
  result.hasDateCreated = NO;
  result.dateCreated = 0L;
  return self;
}
- (BOOL) hasInputEncodings {
  return result.hasInputEncodings;
}
- (NSString*) inputEncodings {
  return result.inputEncodings;
}
- (SearchEngineSpecifics_Builder*) setInputEncodings:(NSString*) value {
  result.hasInputEncodings = YES;
  result.inputEncodings = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearInputEncodings {
  result.hasInputEncodings = NO;
  result.inputEncodings = @"";
  return self;
}
- (BOOL) hasShowInDefaultList {
  return result.hasShowInDefaultList;
}
- (BOOL) showInDefaultList {
  return result.showInDefaultList;
}
- (SearchEngineSpecifics_Builder*) setShowInDefaultList:(BOOL) value {
  result.hasShowInDefaultList = YES;
  result.showInDefaultList = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearShowInDefaultList {
  result.hasShowInDefaultList = NO;
  result.showInDefaultList = NO;
  return self;
}
- (BOOL) hasSuggestionsUrl {
  return result.hasSuggestionsUrl;
}
- (NSString*) suggestionsUrl {
  return result.suggestionsUrl;
}
- (SearchEngineSpecifics_Builder*) setSuggestionsUrl:(NSString*) value {
  result.hasSuggestionsUrl = YES;
  result.suggestionsUrl = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearSuggestionsUrl {
  result.hasSuggestionsUrl = NO;
  result.suggestionsUrl = @"";
  return self;
}
- (BOOL) hasPrepopulateId {
  return result.hasPrepopulateId;
}
- (int32_t) prepopulateId {
  return result.prepopulateId;
}
- (SearchEngineSpecifics_Builder*) setPrepopulateId:(int32_t) value {
  result.hasPrepopulateId = YES;
  result.prepopulateId = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearPrepopulateId {
  result.hasPrepopulateId = NO;
  result.prepopulateId = 0;
  return self;
}
- (BOOL) hasAutogenerateKeyword {
  return result.hasAutogenerateKeyword;
}
- (BOOL) autogenerateKeyword {
  return result.autogenerateKeyword;
}
- (SearchEngineSpecifics_Builder*) setAutogenerateKeyword:(BOOL) value {
  result.hasAutogenerateKeyword = YES;
  result.autogenerateKeyword = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearAutogenerateKeyword {
  result.hasAutogenerateKeyword = NO;
  result.autogenerateKeyword = NO;
  return self;
}
- (BOOL) hasInstantUrl {
  return result.hasInstantUrl;
}
- (NSString*) instantUrl {
  return result.instantUrl;
}
- (SearchEngineSpecifics_Builder*) setInstantUrl:(NSString*) value {
  result.hasInstantUrl = YES;
  result.instantUrl = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearInstantUrl {
  result.hasInstantUrl = NO;
  result.instantUrl = @"";
  return self;
}
- (BOOL) hasLastModified {
  return result.hasLastModified;
}
- (int64_t) lastModified {
  return result.lastModified;
}
- (SearchEngineSpecifics_Builder*) setLastModified:(int64_t) value {
  result.hasLastModified = YES;
  result.lastModified = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearLastModified {
  result.hasLastModified = NO;
  result.lastModified = 0L;
  return self;
}
- (BOOL) hasSyncGuid {
  return result.hasSyncGuid;
}
- (NSString*) syncGuid {
  return result.syncGuid;
}
- (SearchEngineSpecifics_Builder*) setSyncGuid:(NSString*) value {
  result.hasSyncGuid = YES;
  result.syncGuid = value;
  return self;
}
- (SearchEngineSpecifics_Builder*) clearSyncGuid {
  result.hasSyncGuid = NO;
  result.syncGuid = @"";
  return self;
}
@end

