// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "AppNotificationSpecifics.pb.h"
#import "AppSettingSpecifics.pb.h"
#import "AppSpecifics.pb.h"
#import "AutofillSpecifics.pb.h"
#import "BookmarkSpecifics.pb.h"
#import "GetUpdatesCallerInfo.pb.h"
#import "ExtensionSettingSpecifics.pb.h"
#import "ExtensionSpecifics.pb.h"
#import "NigoriSpecifics.pb.h"
#import "PasswordSpecifics.pb.h"
#import "PreferenceSpecifics.pb.h"
#import "SearchEngineSpecifics.pb.h"
#import "SessionSpecifics.pb.h"
#import "ThemeSpecifics.pb.h"
#import "TypedUrlSpecifics.pb.h"
#import "Encryption.pb.h"
#import "SyncEnums.pb.h"
#import "ClientCommands.pb.h"
#import "ClientDebugInfo.pb.h"

@class AppNotification;
@class AppNotificationSettings;
@class AppNotificationSettings_Builder;
@class AppNotification_Builder;
@class AppSettingSpecifics;
@class AppSettingSpecifics_Builder;
@class AppSpecifics;
@class AppSpecifics_Builder;
@class AuthenticateMessage;
@class AuthenticateMessage_Builder;
@class AuthenticateResponse;
@class AuthenticateResponse_Builder;
@class AutofillProfileSpecifics;
@class AutofillProfileSpecifics_Builder;
@class AutofillSpecifics;
@class AutofillSpecifics_Builder;
@class BookmarkSpecifics;
@class BookmarkSpecifics_Builder;
@class ChromiumExtensionsActivity;
@class ChromiumExtensionsActivity_Builder;
@class ClearUserDataMessage;
@class ClearUserDataMessage_Builder;
@class ClearUserDataResponse;
@class ClearUserDataResponse_Builder;
@class ClientCommand;
@class ClientCommand_Builder;
@class ClientToServerMessage;
@class ClientToServerMessage_Builder;
@class ClientToServerResponse;
@class ClientToServerResponse_Builder;
@class ClientToServerResponse_Error;
@class ClientToServerResponse_Error_Builder;
@class CommitMessage;
@class CommitMessage_Builder;
@class CommitResponse;
@class CommitResponse_Builder;
@class CommitResponse_EntryResponse;
@class CommitResponse_EntryResponse_Builder;
@class DataTypeProgressMarker;
@class DataTypeProgressMarker_Builder;
@class DebugEventInfo;
@class DebugEventInfo_Builder;
@class DebugInfo;
@class DebugInfo_Builder;
@class DeviceInformation;
@class DeviceInformation_Builder;
@class EncryptedData;
@class EncryptedData_Builder;
@class EntitySpecifics;
@class EntitySpecifics_Builder;
@class ExtensionSettingSpecifics;
@class ExtensionSettingSpecifics_Builder;
@class ExtensionSpecifics;
@class ExtensionSpecifics_Builder;
@class GetUpdatesCallerInfo;
@class GetUpdatesCallerInfo_Builder;
@class GetUpdatesMessage;
@class GetUpdatesMessage_Builder;
@class GetUpdatesMetadataResponse;
@class GetUpdatesMetadataResponse_Builder;
@class GetUpdatesResponse;
@class GetUpdatesResponse_Builder;
@class GetUpdatesStreamingResponse;
@class GetUpdatesStreamingResponse_Builder;
@class NigoriKey;
@class NigoriKeyBag;
@class NigoriKeyBag_Builder;
@class NigoriKey_Builder;
@class NigoriSpecifics;
@class NigoriSpecifics_Builder;
@class PasswordSpecifics;
@class PasswordSpecificsData;
@class PasswordSpecificsData_Builder;
@class PasswordSpecifics_Builder;
@class PreferenceSpecifics;
@class PreferenceSpecifics_Builder;
@class ProfilingData;
@class ProfilingData_Builder;
@class SearchEngineSpecifics;
@class SearchEngineSpecifics_Builder;
@class SessionHeader;
@class SessionHeader_Builder;
@class SessionSpecifics;
@class SessionSpecifics_Builder;
@class SessionTab;
@class SessionTab_Builder;
@class SessionWindow;
@class SessionWindow_Builder;
@class SyncCycleCompletedEventInfo;
@class SyncCycleCompletedEventInfo_Builder;
@class SyncEntity;
@class SyncEntity_BookmarkData;
@class SyncEntity_BookmarkData_Builder;
@class SyncEntity_Builder;
@class SyncEnums;
@class SyncEnums_Builder;
@class TabNavigation;
@class TabNavigation_Builder;
@class ThemeSpecifics;
@class ThemeSpecifics_Builder;
@class ThrottleParameters;
@class ThrottleParameters_Builder;
@class TypedUrlSpecifics;
@class TypedUrlSpecifics_Builder;
@class UserIdentification;
@class UserIdentification_Builder;
typedef enum {
  ClientToServerMessage_ContentsCommit = 1,
  ClientToServerMessage_ContentsGetUpdates = 2,
  ClientToServerMessage_ContentsAuthenticate = 3,
  ClientToServerMessage_ContentsClearData = 4,
} ClientToServerMessage_Contents;

BOOL ClientToServerMessage_ContentsIsValidValue(ClientToServerMessage_Contents value);

typedef enum {
  CommitResponse_ResponseTypeSuccess = 1,
  CommitResponse_ResponseTypeConflict = 2,
  CommitResponse_ResponseTypeRetry = 3,
  CommitResponse_ResponseTypeInvalidMessage = 4,
  CommitResponse_ResponseTypeOverQuota = 5,
  CommitResponse_ResponseTypeTransientError = 6,
} CommitResponse_ResponseType;

BOOL CommitResponse_ResponseTypeIsValidValue(CommitResponse_ResponseType value);


@interface SyncRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ProfilingData : PBGeneratedMessage {
@private
  BOOL hasMetaDataWriteTime_:1;
  BOOL hasFileDataWriteTime_:1;
  BOOL hasUserLookupTime_:1;
  BOOL hasMetaDataReadTime_:1;
  BOOL hasFileDataReadTime_:1;
  BOOL hasTotalRequestTime_:1;
  int64_t metaDataWriteTime;
  int64_t fileDataWriteTime;
  int64_t userLookupTime;
  int64_t metaDataReadTime;
  int64_t fileDataReadTime;
  int64_t totalRequestTime;
}
- (BOOL) hasMetaDataWriteTime;
- (BOOL) hasFileDataWriteTime;
- (BOOL) hasUserLookupTime;
- (BOOL) hasMetaDataReadTime;
- (BOOL) hasFileDataReadTime;
- (BOOL) hasTotalRequestTime;
@property (readonly) int64_t metaDataWriteTime;
@property (readonly) int64_t fileDataWriteTime;
@property (readonly) int64_t userLookupTime;
@property (readonly) int64_t metaDataReadTime;
@property (readonly) int64_t fileDataReadTime;
@property (readonly) int64_t totalRequestTime;

+ (ProfilingData*) defaultInstance;
- (ProfilingData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProfilingData_Builder*) builder;
+ (ProfilingData_Builder*) builder;
+ (ProfilingData_Builder*) builderWithPrototype:(ProfilingData*) prototype;

+ (ProfilingData*) parseFromData:(NSData*) data;
+ (ProfilingData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProfilingData*) parseFromInputStream:(NSInputStream*) input;
+ (ProfilingData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProfilingData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProfilingData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProfilingData_Builder : PBGeneratedMessage_Builder {
@private
  ProfilingData* result;
}

- (ProfilingData*) defaultInstance;

- (ProfilingData_Builder*) clear;
- (ProfilingData_Builder*) clone;

- (ProfilingData*) build;
- (ProfilingData*) buildPartial;

- (ProfilingData_Builder*) mergeFrom:(ProfilingData*) other;
- (ProfilingData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProfilingData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMetaDataWriteTime;
- (int64_t) metaDataWriteTime;
- (ProfilingData_Builder*) setMetaDataWriteTime:(int64_t) value;
- (ProfilingData_Builder*) clearMetaDataWriteTime;

- (BOOL) hasFileDataWriteTime;
- (int64_t) fileDataWriteTime;
- (ProfilingData_Builder*) setFileDataWriteTime:(int64_t) value;
- (ProfilingData_Builder*) clearFileDataWriteTime;

- (BOOL) hasUserLookupTime;
- (int64_t) userLookupTime;
- (ProfilingData_Builder*) setUserLookupTime:(int64_t) value;
- (ProfilingData_Builder*) clearUserLookupTime;

- (BOOL) hasMetaDataReadTime;
- (int64_t) metaDataReadTime;
- (ProfilingData_Builder*) setMetaDataReadTime:(int64_t) value;
- (ProfilingData_Builder*) clearMetaDataReadTime;

- (BOOL) hasFileDataReadTime;
- (int64_t) fileDataReadTime;
- (ProfilingData_Builder*) setFileDataReadTime:(int64_t) value;
- (ProfilingData_Builder*) clearFileDataReadTime;

- (BOOL) hasTotalRequestTime;
- (int64_t) totalRequestTime;
- (ProfilingData_Builder*) setTotalRequestTime:(int64_t) value;
- (ProfilingData_Builder*) clearTotalRequestTime;
@end

@interface EntitySpecifics : PBGeneratedMessage {
@private
  BOOL hasEncrypted_:1;
  BOOL hasAutofill_:1;
  BOOL hasBookmark_:1;
  BOOL hasPreference_:1;
  BOOL hasTypedUrl_:1;
  BOOL hasTheme_:1;
  BOOL hasAppNotification_:1;
  BOOL hasPassword_:1;
  BOOL hasNigori_:1;
  BOOL hasExtension_:1;
  BOOL hasApp_:1;
  BOOL hasSession_:1;
  BOOL hasAutofillProfile_:1;
  BOOL hasSearchEngine_:1;
  BOOL hasExtensionSetting_:1;
  BOOL hasAppSetting_:1;
  EncryptedData* encrypted;
  AutofillSpecifics* autofill;
  BookmarkSpecifics* bookmark;
  PreferenceSpecifics* preference;
  TypedUrlSpecifics* typedUrl;
  ThemeSpecifics* theme;
  AppNotification* appNotification;
  PasswordSpecifics* password;
  NigoriSpecifics* nigori;
  ExtensionSpecifics* extension;
  AppSpecifics* app;
  SessionSpecifics* session;
  AutofillProfileSpecifics* autofillProfile;
  SearchEngineSpecifics* searchEngine;
  ExtensionSettingSpecifics* extensionSetting;
  AppSettingSpecifics* appSetting;
}
- (BOOL) hasEncrypted;
- (BOOL) hasAutofill;
- (BOOL) hasBookmark;
- (BOOL) hasPreference;
- (BOOL) hasTypedUrl;
- (BOOL) hasTheme;
- (BOOL) hasAppNotification;
- (BOOL) hasPassword;
- (BOOL) hasNigori;
- (BOOL) hasExtension;
- (BOOL) hasApp;
- (BOOL) hasSession;
- (BOOL) hasAutofillProfile;
- (BOOL) hasSearchEngine;
- (BOOL) hasExtensionSetting;
- (BOOL) hasAppSetting;
@property (readonly, retain) EncryptedData* encrypted;
@property (readonly, retain) AutofillSpecifics* autofill;
@property (readonly, retain) BookmarkSpecifics* bookmark;
@property (readonly, retain) PreferenceSpecifics* preference;
@property (readonly, retain) TypedUrlSpecifics* typedUrl;
@property (readonly, retain) ThemeSpecifics* theme;
@property (readonly, retain) AppNotification* appNotification;
@property (readonly, retain) PasswordSpecifics* password;
@property (readonly, retain) NigoriSpecifics* nigori;
@property (readonly, retain) ExtensionSpecifics* extension;
@property (readonly, retain) AppSpecifics* app;
@property (readonly, retain) SessionSpecifics* session;
@property (readonly, retain) AutofillProfileSpecifics* autofillProfile;
@property (readonly, retain) SearchEngineSpecifics* searchEngine;
@property (readonly, retain) ExtensionSettingSpecifics* extensionSetting;
@property (readonly, retain) AppSettingSpecifics* appSetting;

+ (EntitySpecifics*) defaultInstance;
- (EntitySpecifics*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EntitySpecifics_Builder*) builder;
+ (EntitySpecifics_Builder*) builder;
+ (EntitySpecifics_Builder*) builderWithPrototype:(EntitySpecifics*) prototype;

+ (EntitySpecifics*) parseFromData:(NSData*) data;
+ (EntitySpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EntitySpecifics*) parseFromInputStream:(NSInputStream*) input;
+ (EntitySpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EntitySpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EntitySpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EntitySpecifics_Builder : PBGeneratedMessage_Builder {
@private
  EntitySpecifics* result;
}

- (EntitySpecifics*) defaultInstance;

- (EntitySpecifics_Builder*) clear;
- (EntitySpecifics_Builder*) clone;

- (EntitySpecifics*) build;
- (EntitySpecifics*) buildPartial;

- (EntitySpecifics_Builder*) mergeFrom:(EntitySpecifics*) other;
- (EntitySpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EntitySpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEncrypted;
- (EncryptedData*) encrypted;
- (EntitySpecifics_Builder*) setEncrypted:(EncryptedData*) value;
- (EntitySpecifics_Builder*) setEncryptedBuilder:(EncryptedData_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeEncrypted:(EncryptedData*) value;
- (EntitySpecifics_Builder*) clearEncrypted;

- (BOOL) hasAutofill;
- (AutofillSpecifics*) autofill;
- (EntitySpecifics_Builder*) setAutofill:(AutofillSpecifics*) value;
- (EntitySpecifics_Builder*) setAutofillBuilder:(AutofillSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeAutofill:(AutofillSpecifics*) value;
- (EntitySpecifics_Builder*) clearAutofill;

- (BOOL) hasBookmark;
- (BookmarkSpecifics*) bookmark;
- (EntitySpecifics_Builder*) setBookmark:(BookmarkSpecifics*) value;
- (EntitySpecifics_Builder*) setBookmarkBuilder:(BookmarkSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeBookmark:(BookmarkSpecifics*) value;
- (EntitySpecifics_Builder*) clearBookmark;

- (BOOL) hasPreference;
- (PreferenceSpecifics*) preference;
- (EntitySpecifics_Builder*) setPreference:(PreferenceSpecifics*) value;
- (EntitySpecifics_Builder*) setPreferenceBuilder:(PreferenceSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergePreference:(PreferenceSpecifics*) value;
- (EntitySpecifics_Builder*) clearPreference;

- (BOOL) hasTypedUrl;
- (TypedUrlSpecifics*) typedUrl;
- (EntitySpecifics_Builder*) setTypedUrl:(TypedUrlSpecifics*) value;
- (EntitySpecifics_Builder*) setTypedUrlBuilder:(TypedUrlSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeTypedUrl:(TypedUrlSpecifics*) value;
- (EntitySpecifics_Builder*) clearTypedUrl;

- (BOOL) hasTheme;
- (ThemeSpecifics*) theme;
- (EntitySpecifics_Builder*) setTheme:(ThemeSpecifics*) value;
- (EntitySpecifics_Builder*) setThemeBuilder:(ThemeSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeTheme:(ThemeSpecifics*) value;
- (EntitySpecifics_Builder*) clearTheme;

- (BOOL) hasAppNotification;
- (AppNotification*) appNotification;
- (EntitySpecifics_Builder*) setAppNotification:(AppNotification*) value;
- (EntitySpecifics_Builder*) setAppNotificationBuilder:(AppNotification_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeAppNotification:(AppNotification*) value;
- (EntitySpecifics_Builder*) clearAppNotification;

- (BOOL) hasPassword;
- (PasswordSpecifics*) password;
- (EntitySpecifics_Builder*) setPassword:(PasswordSpecifics*) value;
- (EntitySpecifics_Builder*) setPasswordBuilder:(PasswordSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergePassword:(PasswordSpecifics*) value;
- (EntitySpecifics_Builder*) clearPassword;

- (BOOL) hasNigori;
- (NigoriSpecifics*) nigori;
- (EntitySpecifics_Builder*) setNigori:(NigoriSpecifics*) value;
- (EntitySpecifics_Builder*) setNigoriBuilder:(NigoriSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeNigori:(NigoriSpecifics*) value;
- (EntitySpecifics_Builder*) clearNigori;

- (BOOL) hasExtension;
- (ExtensionSpecifics*) extension;
- (EntitySpecifics_Builder*) setExtension:(ExtensionSpecifics*) value;
- (EntitySpecifics_Builder*) setExtensionBuilder:(ExtensionSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeExtension:(ExtensionSpecifics*) value;
- (EntitySpecifics_Builder*) clearExtension;

- (BOOL) hasApp;
- (AppSpecifics*) app;
- (EntitySpecifics_Builder*) setApp:(AppSpecifics*) value;
- (EntitySpecifics_Builder*) setAppBuilder:(AppSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeApp:(AppSpecifics*) value;
- (EntitySpecifics_Builder*) clearApp;

- (BOOL) hasSession;
- (SessionSpecifics*) session;
- (EntitySpecifics_Builder*) setSession:(SessionSpecifics*) value;
- (EntitySpecifics_Builder*) setSessionBuilder:(SessionSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeSession:(SessionSpecifics*) value;
- (EntitySpecifics_Builder*) clearSession;

- (BOOL) hasAutofillProfile;
- (AutofillProfileSpecifics*) autofillProfile;
- (EntitySpecifics_Builder*) setAutofillProfile:(AutofillProfileSpecifics*) value;
- (EntitySpecifics_Builder*) setAutofillProfileBuilder:(AutofillProfileSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeAutofillProfile:(AutofillProfileSpecifics*) value;
- (EntitySpecifics_Builder*) clearAutofillProfile;

- (BOOL) hasSearchEngine;
- (SearchEngineSpecifics*) searchEngine;
- (EntitySpecifics_Builder*) setSearchEngine:(SearchEngineSpecifics*) value;
- (EntitySpecifics_Builder*) setSearchEngineBuilder:(SearchEngineSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeSearchEngine:(SearchEngineSpecifics*) value;
- (EntitySpecifics_Builder*) clearSearchEngine;

- (BOOL) hasExtensionSetting;
- (ExtensionSettingSpecifics*) extensionSetting;
- (EntitySpecifics_Builder*) setExtensionSetting:(ExtensionSettingSpecifics*) value;
- (EntitySpecifics_Builder*) setExtensionSettingBuilder:(ExtensionSettingSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeExtensionSetting:(ExtensionSettingSpecifics*) value;
- (EntitySpecifics_Builder*) clearExtensionSetting;

- (BOOL) hasAppSetting;
- (AppSettingSpecifics*) appSetting;
- (EntitySpecifics_Builder*) setAppSetting:(AppSettingSpecifics*) value;
- (EntitySpecifics_Builder*) setAppSettingBuilder:(AppSettingSpecifics_Builder*) builderForValue;
- (EntitySpecifics_Builder*) mergeAppSetting:(AppSettingSpecifics*) value;
- (EntitySpecifics_Builder*) clearAppSetting;
@end

@interface SyncEntity : PBGeneratedMessage {
@private
  BOOL hasFolder_:1;
  BOOL hasDeleted_:1;
  BOOL hasPositionInParent_:1;
  BOOL hasSyncTimestamp_:1;
  BOOL hasCtime_:1;
  BOOL hasMtime_:1;
  BOOL hasVersion_:1;
  BOOL hasName_:1;
  BOOL hasNonUniqueName_:1;
  BOOL hasServerDefinedUniqueTag_:1;
  BOOL hasClientDefinedUniqueTag_:1;
  BOOL hasOldParentId_:1;
  BOOL hasInsertAfterItemId_:1;
  BOOL hasParentIdString_:1;
  BOOL hasOriginatorCacheGuid_:1;
  BOOL hasOriginatorClientItemId_:1;
  BOOL hasIdString_:1;
  BOOL hasBookmarkData_:1;
  BOOL hasSpecifics_:1;
  BOOL hasOrdinalInParent_:1;
  BOOL folder_:1;
  BOOL deleted_:1;
  int64_t positionInParent;
  int64_t syncTimestamp;
  int64_t ctime;
  int64_t mtime;
  int64_t version;
  NSString* name;
  NSString* nonUniqueName;
  NSString* serverDefinedUniqueTag;
  NSString* clientDefinedUniqueTag;
  NSString* oldParentId;
  NSString* insertAfterItemId;
  NSString* parentIdString;
  NSString* originatorCacheGuid;
  NSString* originatorClientItemId;
  NSString* idString;
  SyncEntity_BookmarkData* bookmarkData;
  EntitySpecifics* specifics;
  NSData* ordinalInParent;
}
- (BOOL) hasIdString;
- (BOOL) hasParentIdString;
- (BOOL) hasOldParentId;
- (BOOL) hasVersion;
- (BOOL) hasMtime;
- (BOOL) hasCtime;
- (BOOL) hasName;
- (BOOL) hasNonUniqueName;
- (BOOL) hasSyncTimestamp;
- (BOOL) hasServerDefinedUniqueTag;
- (BOOL) hasBookmarkData;
- (BOOL) hasPositionInParent;
- (BOOL) hasInsertAfterItemId;
- (BOOL) hasDeleted;
- (BOOL) hasOriginatorCacheGuid;
- (BOOL) hasOriginatorClientItemId;
- (BOOL) hasSpecifics;
- (BOOL) hasFolder;
- (BOOL) hasClientDefinedUniqueTag;
- (BOOL) hasOrdinalInParent;
@property (readonly, retain) NSString* idString;
@property (readonly, retain) NSString* parentIdString;
@property (readonly, retain) NSString* oldParentId;
@property (readonly) int64_t version;
@property (readonly) int64_t mtime;
@property (readonly) int64_t ctime;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* nonUniqueName;
@property (readonly) int64_t syncTimestamp;
@property (readonly, retain) NSString* serverDefinedUniqueTag;
@property (readonly, retain) SyncEntity_BookmarkData* bookmarkData;
@property (readonly) int64_t positionInParent;
@property (readonly, retain) NSString* insertAfterItemId;
- (BOOL) deleted;
@property (readonly, retain) NSString* originatorCacheGuid;
@property (readonly, retain) NSString* originatorClientItemId;
@property (readonly, retain) EntitySpecifics* specifics;
- (BOOL) folder;
@property (readonly, retain) NSString* clientDefinedUniqueTag;
@property (readonly, retain) NSData* ordinalInParent;

+ (SyncEntity*) defaultInstance;
- (SyncEntity*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SyncEntity_Builder*) builder;
+ (SyncEntity_Builder*) builder;
+ (SyncEntity_Builder*) builderWithPrototype:(SyncEntity*) prototype;

+ (SyncEntity*) parseFromData:(NSData*) data;
+ (SyncEntity*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncEntity*) parseFromInputStream:(NSInputStream*) input;
+ (SyncEntity*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncEntity*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SyncEntity*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SyncEntity_BookmarkData : PBGeneratedMessage {
@private
  BOOL hasBookmarkFolder_:1;
  BOOL hasBookmarkUrl_:1;
  BOOL hasBookmarkFavicon_:1;
  BOOL bookmarkFolder_:1;
  NSString* bookmarkUrl;
  NSData* bookmarkFavicon;
}
- (BOOL) hasBookmarkFolder;
- (BOOL) hasBookmarkUrl;
- (BOOL) hasBookmarkFavicon;
- (BOOL) bookmarkFolder;
@property (readonly, retain) NSString* bookmarkUrl;
@property (readonly, retain) NSData* bookmarkFavicon;

+ (SyncEntity_BookmarkData*) defaultInstance;
- (SyncEntity_BookmarkData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SyncEntity_BookmarkData_Builder*) builder;
+ (SyncEntity_BookmarkData_Builder*) builder;
+ (SyncEntity_BookmarkData_Builder*) builderWithPrototype:(SyncEntity_BookmarkData*) prototype;

+ (SyncEntity_BookmarkData*) parseFromData:(NSData*) data;
+ (SyncEntity_BookmarkData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncEntity_BookmarkData*) parseFromInputStream:(NSInputStream*) input;
+ (SyncEntity_BookmarkData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncEntity_BookmarkData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SyncEntity_BookmarkData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SyncEntity_BookmarkData_Builder : PBGeneratedMessage_Builder {
@private
  SyncEntity_BookmarkData* result;
}

- (SyncEntity_BookmarkData*) defaultInstance;

- (SyncEntity_BookmarkData_Builder*) clear;
- (SyncEntity_BookmarkData_Builder*) clone;

- (SyncEntity_BookmarkData*) build;
- (SyncEntity_BookmarkData*) buildPartial;

- (SyncEntity_BookmarkData_Builder*) mergeFrom:(SyncEntity_BookmarkData*) other;
- (SyncEntity_BookmarkData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SyncEntity_BookmarkData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBookmarkFolder;
- (BOOL) bookmarkFolder;
- (SyncEntity_BookmarkData_Builder*) setBookmarkFolder:(BOOL) value;
- (SyncEntity_BookmarkData_Builder*) clearBookmarkFolder;

- (BOOL) hasBookmarkUrl;
- (NSString*) bookmarkUrl;
- (SyncEntity_BookmarkData_Builder*) setBookmarkUrl:(NSString*) value;
- (SyncEntity_BookmarkData_Builder*) clearBookmarkUrl;

- (BOOL) hasBookmarkFavicon;
- (NSData*) bookmarkFavicon;
- (SyncEntity_BookmarkData_Builder*) setBookmarkFavicon:(NSData*) value;
- (SyncEntity_BookmarkData_Builder*) clearBookmarkFavicon;
@end

@interface SyncEntity_Builder : PBGeneratedMessage_Builder {
@private
  SyncEntity* result;
}

- (SyncEntity*) defaultInstance;

- (SyncEntity_Builder*) clear;
- (SyncEntity_Builder*) clone;

- (SyncEntity*) build;
- (SyncEntity*) buildPartial;

- (SyncEntity_Builder*) mergeFrom:(SyncEntity*) other;
- (SyncEntity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SyncEntity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIdString;
- (NSString*) idString;
- (SyncEntity_Builder*) setIdString:(NSString*) value;
- (SyncEntity_Builder*) clearIdString;

- (BOOL) hasParentIdString;
- (NSString*) parentIdString;
- (SyncEntity_Builder*) setParentIdString:(NSString*) value;
- (SyncEntity_Builder*) clearParentIdString;

- (BOOL) hasOldParentId;
- (NSString*) oldParentId;
- (SyncEntity_Builder*) setOldParentId:(NSString*) value;
- (SyncEntity_Builder*) clearOldParentId;

- (BOOL) hasVersion;
- (int64_t) version;
- (SyncEntity_Builder*) setVersion:(int64_t) value;
- (SyncEntity_Builder*) clearVersion;

- (BOOL) hasMtime;
- (int64_t) mtime;
- (SyncEntity_Builder*) setMtime:(int64_t) value;
- (SyncEntity_Builder*) clearMtime;

- (BOOL) hasCtime;
- (int64_t) ctime;
- (SyncEntity_Builder*) setCtime:(int64_t) value;
- (SyncEntity_Builder*) clearCtime;

- (BOOL) hasName;
- (NSString*) name;
- (SyncEntity_Builder*) setName:(NSString*) value;
- (SyncEntity_Builder*) clearName;

- (BOOL) hasNonUniqueName;
- (NSString*) nonUniqueName;
- (SyncEntity_Builder*) setNonUniqueName:(NSString*) value;
- (SyncEntity_Builder*) clearNonUniqueName;

- (BOOL) hasSyncTimestamp;
- (int64_t) syncTimestamp;
- (SyncEntity_Builder*) setSyncTimestamp:(int64_t) value;
- (SyncEntity_Builder*) clearSyncTimestamp;

- (BOOL) hasServerDefinedUniqueTag;
- (NSString*) serverDefinedUniqueTag;
- (SyncEntity_Builder*) setServerDefinedUniqueTag:(NSString*) value;
- (SyncEntity_Builder*) clearServerDefinedUniqueTag;

- (BOOL) hasBookmarkData;
- (SyncEntity_BookmarkData*) bookmarkData;
- (SyncEntity_Builder*) setBookmarkData:(SyncEntity_BookmarkData*) value;
- (SyncEntity_Builder*) setBookmarkDataBuilder:(SyncEntity_BookmarkData_Builder*) builderForValue;
- (SyncEntity_Builder*) mergeBookmarkData:(SyncEntity_BookmarkData*) value;
- (SyncEntity_Builder*) clearBookmarkData;

- (BOOL) hasPositionInParent;
- (int64_t) positionInParent;
- (SyncEntity_Builder*) setPositionInParent:(int64_t) value;
- (SyncEntity_Builder*) clearPositionInParent;

- (BOOL) hasInsertAfterItemId;
- (NSString*) insertAfterItemId;
- (SyncEntity_Builder*) setInsertAfterItemId:(NSString*) value;
- (SyncEntity_Builder*) clearInsertAfterItemId;

- (BOOL) hasDeleted;
- (BOOL) deleted;
- (SyncEntity_Builder*) setDeleted:(BOOL) value;
- (SyncEntity_Builder*) clearDeleted;

- (BOOL) hasOriginatorCacheGuid;
- (NSString*) originatorCacheGuid;
- (SyncEntity_Builder*) setOriginatorCacheGuid:(NSString*) value;
- (SyncEntity_Builder*) clearOriginatorCacheGuid;

- (BOOL) hasOriginatorClientItemId;
- (NSString*) originatorClientItemId;
- (SyncEntity_Builder*) setOriginatorClientItemId:(NSString*) value;
- (SyncEntity_Builder*) clearOriginatorClientItemId;

- (BOOL) hasSpecifics;
- (EntitySpecifics*) specifics;
- (SyncEntity_Builder*) setSpecifics:(EntitySpecifics*) value;
- (SyncEntity_Builder*) setSpecificsBuilder:(EntitySpecifics_Builder*) builderForValue;
- (SyncEntity_Builder*) mergeSpecifics:(EntitySpecifics*) value;
- (SyncEntity_Builder*) clearSpecifics;

- (BOOL) hasFolder;
- (BOOL) folder;
- (SyncEntity_Builder*) setFolder:(BOOL) value;
- (SyncEntity_Builder*) clearFolder;

- (BOOL) hasClientDefinedUniqueTag;
- (NSString*) clientDefinedUniqueTag;
- (SyncEntity_Builder*) setClientDefinedUniqueTag:(NSString*) value;
- (SyncEntity_Builder*) clearClientDefinedUniqueTag;

- (BOOL) hasOrdinalInParent;
- (NSData*) ordinalInParent;
- (SyncEntity_Builder*) setOrdinalInParent:(NSData*) value;
- (SyncEntity_Builder*) clearOrdinalInParent;
@end

@interface ChromiumExtensionsActivity : PBGeneratedMessage {
@private
  BOOL hasExtensionId_:1;
  BOOL hasBookmarkWritesSinceLastCommit_:1;
  NSString* extensionId;
  int32_t bookmarkWritesSinceLastCommit;
}
- (BOOL) hasExtensionId;
- (BOOL) hasBookmarkWritesSinceLastCommit;
@property (readonly, retain) NSString* extensionId;
@property (readonly) int32_t bookmarkWritesSinceLastCommit;

+ (ChromiumExtensionsActivity*) defaultInstance;
- (ChromiumExtensionsActivity*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChromiumExtensionsActivity_Builder*) builder;
+ (ChromiumExtensionsActivity_Builder*) builder;
+ (ChromiumExtensionsActivity_Builder*) builderWithPrototype:(ChromiumExtensionsActivity*) prototype;

+ (ChromiumExtensionsActivity*) parseFromData:(NSData*) data;
+ (ChromiumExtensionsActivity*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChromiumExtensionsActivity*) parseFromInputStream:(NSInputStream*) input;
+ (ChromiumExtensionsActivity*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChromiumExtensionsActivity*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChromiumExtensionsActivity*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChromiumExtensionsActivity_Builder : PBGeneratedMessage_Builder {
@private
  ChromiumExtensionsActivity* result;
}

- (ChromiumExtensionsActivity*) defaultInstance;

- (ChromiumExtensionsActivity_Builder*) clear;
- (ChromiumExtensionsActivity_Builder*) clone;

- (ChromiumExtensionsActivity*) build;
- (ChromiumExtensionsActivity*) buildPartial;

- (ChromiumExtensionsActivity_Builder*) mergeFrom:(ChromiumExtensionsActivity*) other;
- (ChromiumExtensionsActivity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChromiumExtensionsActivity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasExtensionId;
- (NSString*) extensionId;
- (ChromiumExtensionsActivity_Builder*) setExtensionId:(NSString*) value;
- (ChromiumExtensionsActivity_Builder*) clearExtensionId;

- (BOOL) hasBookmarkWritesSinceLastCommit;
- (int32_t) bookmarkWritesSinceLastCommit;
- (ChromiumExtensionsActivity_Builder*) setBookmarkWritesSinceLastCommit:(int32_t) value;
- (ChromiumExtensionsActivity_Builder*) clearBookmarkWritesSinceLastCommit;
@end

@interface CommitMessage : PBGeneratedMessage {
@private
  BOOL hasCacheGuid_:1;
  NSString* cacheGuid;
  NSMutableArray* mutableEntriesList;
  NSMutableArray* mutableExtensionsActivityList;
}
- (BOOL) hasCacheGuid;
@property (readonly, retain) NSString* cacheGuid;
- (NSArray*) entriesList;
- (SyncEntity*) entriesAtIndex:(int32_t) index;
- (NSArray*) extensionsActivityList;
- (ChromiumExtensionsActivity*) extensionsActivityAtIndex:(int32_t) index;

+ (CommitMessage*) defaultInstance;
- (CommitMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CommitMessage_Builder*) builder;
+ (CommitMessage_Builder*) builder;
+ (CommitMessage_Builder*) builderWithPrototype:(CommitMessage*) prototype;

+ (CommitMessage*) parseFromData:(NSData*) data;
+ (CommitMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommitMessage*) parseFromInputStream:(NSInputStream*) input;
+ (CommitMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommitMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CommitMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CommitMessage_Builder : PBGeneratedMessage_Builder {
@private
  CommitMessage* result;
}

- (CommitMessage*) defaultInstance;

- (CommitMessage_Builder*) clear;
- (CommitMessage_Builder*) clone;

- (CommitMessage*) build;
- (CommitMessage*) buildPartial;

- (CommitMessage_Builder*) mergeFrom:(CommitMessage*) other;
- (CommitMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CommitMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) entriesList;
- (SyncEntity*) entriesAtIndex:(int32_t) index;
- (CommitMessage_Builder*) replaceEntriesAtIndex:(int32_t) index with:(SyncEntity*) value;
- (CommitMessage_Builder*) addEntries:(SyncEntity*) value;
- (CommitMessage_Builder*) addAllEntries:(NSArray*) values;
- (CommitMessage_Builder*) clearEntriesList;

- (BOOL) hasCacheGuid;
- (NSString*) cacheGuid;
- (CommitMessage_Builder*) setCacheGuid:(NSString*) value;
- (CommitMessage_Builder*) clearCacheGuid;

- (NSArray*) extensionsActivityList;
- (ChromiumExtensionsActivity*) extensionsActivityAtIndex:(int32_t) index;
- (CommitMessage_Builder*) replaceExtensionsActivityAtIndex:(int32_t) index with:(ChromiumExtensionsActivity*) value;
- (CommitMessage_Builder*) addExtensionsActivity:(ChromiumExtensionsActivity*) value;
- (CommitMessage_Builder*) addAllExtensionsActivity:(NSArray*) values;
- (CommitMessage_Builder*) clearExtensionsActivityList;
@end

@interface DataTypeProgressMarker : PBGeneratedMessage {
@private
  BOOL hasTimestampTokenForMigration_:1;
  BOOL hasDataTypeId_:1;
  BOOL hasNotificationHint_:1;
  BOOL hasToken_:1;
  int64_t timestampTokenForMigration;
  int32_t dataTypeId;
  NSString* notificationHint;
  NSData* token;
}
- (BOOL) hasDataTypeId;
- (BOOL) hasToken;
- (BOOL) hasTimestampTokenForMigration;
- (BOOL) hasNotificationHint;
@property (readonly) int32_t dataTypeId;
@property (readonly, retain) NSData* token;
@property (readonly) int64_t timestampTokenForMigration;
@property (readonly, retain) NSString* notificationHint;

+ (DataTypeProgressMarker*) defaultInstance;
- (DataTypeProgressMarker*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DataTypeProgressMarker_Builder*) builder;
+ (DataTypeProgressMarker_Builder*) builder;
+ (DataTypeProgressMarker_Builder*) builderWithPrototype:(DataTypeProgressMarker*) prototype;

+ (DataTypeProgressMarker*) parseFromData:(NSData*) data;
+ (DataTypeProgressMarker*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DataTypeProgressMarker*) parseFromInputStream:(NSInputStream*) input;
+ (DataTypeProgressMarker*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DataTypeProgressMarker*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DataTypeProgressMarker*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DataTypeProgressMarker_Builder : PBGeneratedMessage_Builder {
@private
  DataTypeProgressMarker* result;
}

- (DataTypeProgressMarker*) defaultInstance;

- (DataTypeProgressMarker_Builder*) clear;
- (DataTypeProgressMarker_Builder*) clone;

- (DataTypeProgressMarker*) build;
- (DataTypeProgressMarker*) buildPartial;

- (DataTypeProgressMarker_Builder*) mergeFrom:(DataTypeProgressMarker*) other;
- (DataTypeProgressMarker_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DataTypeProgressMarker_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDataTypeId;
- (int32_t) dataTypeId;
- (DataTypeProgressMarker_Builder*) setDataTypeId:(int32_t) value;
- (DataTypeProgressMarker_Builder*) clearDataTypeId;

- (BOOL) hasToken;
- (NSData*) token;
- (DataTypeProgressMarker_Builder*) setToken:(NSData*) value;
- (DataTypeProgressMarker_Builder*) clearToken;

- (BOOL) hasTimestampTokenForMigration;
- (int64_t) timestampTokenForMigration;
- (DataTypeProgressMarker_Builder*) setTimestampTokenForMigration:(int64_t) value;
- (DataTypeProgressMarker_Builder*) clearTimestampTokenForMigration;

- (BOOL) hasNotificationHint;
- (NSString*) notificationHint;
- (DataTypeProgressMarker_Builder*) setNotificationHint:(NSString*) value;
- (DataTypeProgressMarker_Builder*) clearNotificationHint;
@end

@interface GetUpdatesMessage : PBGeneratedMessage {
@private
  BOOL hasFetchFolders_:1;
  BOOL hasStreaming_:1;
  BOOL hasCreateMobileBookmarksFolder_:1;
  BOOL hasFromTimestamp_:1;
  BOOL hasBatchSize_:1;
  BOOL hasCallerInfo_:1;
  BOOL hasRequestedTypes_:1;
  BOOL fetchFolders_:1;
  BOOL streaming_:1;
  BOOL createMobileBookmarksFolder_:1;
  int64_t fromTimestamp;
  int32_t batchSize;
  GetUpdatesCallerInfo* callerInfo;
  EntitySpecifics* requestedTypes;
  NSMutableArray* mutableFromProgressMarkerList;
}
- (BOOL) hasFromTimestamp;
- (BOOL) hasCallerInfo;
- (BOOL) hasFetchFolders;
- (BOOL) hasRequestedTypes;
- (BOOL) hasBatchSize;
- (BOOL) hasStreaming;
- (BOOL) hasCreateMobileBookmarksFolder;
@property (readonly) int64_t fromTimestamp;
@property (readonly, retain) GetUpdatesCallerInfo* callerInfo;
- (BOOL) fetchFolders;
@property (readonly, retain) EntitySpecifics* requestedTypes;
@property (readonly) int32_t batchSize;
- (BOOL) streaming;
- (BOOL) createMobileBookmarksFolder;
- (NSArray*) fromProgressMarkerList;
- (DataTypeProgressMarker*) fromProgressMarkerAtIndex:(int32_t) index;

+ (GetUpdatesMessage*) defaultInstance;
- (GetUpdatesMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetUpdatesMessage_Builder*) builder;
+ (GetUpdatesMessage_Builder*) builder;
+ (GetUpdatesMessage_Builder*) builderWithPrototype:(GetUpdatesMessage*) prototype;

+ (GetUpdatesMessage*) parseFromData:(NSData*) data;
+ (GetUpdatesMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesMessage*) parseFromInputStream:(NSInputStream*) input;
+ (GetUpdatesMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetUpdatesMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetUpdatesMessage_Builder : PBGeneratedMessage_Builder {
@private
  GetUpdatesMessage* result;
}

- (GetUpdatesMessage*) defaultInstance;

- (GetUpdatesMessage_Builder*) clear;
- (GetUpdatesMessage_Builder*) clone;

- (GetUpdatesMessage*) build;
- (GetUpdatesMessage*) buildPartial;

- (GetUpdatesMessage_Builder*) mergeFrom:(GetUpdatesMessage*) other;
- (GetUpdatesMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetUpdatesMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromTimestamp;
- (int64_t) fromTimestamp;
- (GetUpdatesMessage_Builder*) setFromTimestamp:(int64_t) value;
- (GetUpdatesMessage_Builder*) clearFromTimestamp;

- (BOOL) hasCallerInfo;
- (GetUpdatesCallerInfo*) callerInfo;
- (GetUpdatesMessage_Builder*) setCallerInfo:(GetUpdatesCallerInfo*) value;
- (GetUpdatesMessage_Builder*) setCallerInfoBuilder:(GetUpdatesCallerInfo_Builder*) builderForValue;
- (GetUpdatesMessage_Builder*) mergeCallerInfo:(GetUpdatesCallerInfo*) value;
- (GetUpdatesMessage_Builder*) clearCallerInfo;

- (BOOL) hasFetchFolders;
- (BOOL) fetchFolders;
- (GetUpdatesMessage_Builder*) setFetchFolders:(BOOL) value;
- (GetUpdatesMessage_Builder*) clearFetchFolders;

- (BOOL) hasRequestedTypes;
- (EntitySpecifics*) requestedTypes;
- (GetUpdatesMessage_Builder*) setRequestedTypes:(EntitySpecifics*) value;
- (GetUpdatesMessage_Builder*) setRequestedTypesBuilder:(EntitySpecifics_Builder*) builderForValue;
- (GetUpdatesMessage_Builder*) mergeRequestedTypes:(EntitySpecifics*) value;
- (GetUpdatesMessage_Builder*) clearRequestedTypes;

- (BOOL) hasBatchSize;
- (int32_t) batchSize;
- (GetUpdatesMessage_Builder*) setBatchSize:(int32_t) value;
- (GetUpdatesMessage_Builder*) clearBatchSize;

- (NSArray*) fromProgressMarkerList;
- (DataTypeProgressMarker*) fromProgressMarkerAtIndex:(int32_t) index;
- (GetUpdatesMessage_Builder*) replaceFromProgressMarkerAtIndex:(int32_t) index with:(DataTypeProgressMarker*) value;
- (GetUpdatesMessage_Builder*) addFromProgressMarker:(DataTypeProgressMarker*) value;
- (GetUpdatesMessage_Builder*) addAllFromProgressMarker:(NSArray*) values;
- (GetUpdatesMessage_Builder*) clearFromProgressMarkerList;

- (BOOL) hasStreaming;
- (BOOL) streaming;
- (GetUpdatesMessage_Builder*) setStreaming:(BOOL) value;
- (GetUpdatesMessage_Builder*) clearStreaming;

- (BOOL) hasCreateMobileBookmarksFolder;
- (BOOL) createMobileBookmarksFolder;
- (GetUpdatesMessage_Builder*) setCreateMobileBookmarksFolder:(BOOL) value;
- (GetUpdatesMessage_Builder*) clearCreateMobileBookmarksFolder;
@end

@interface AuthenticateMessage : PBGeneratedMessage {
@private
  BOOL hasAuthToken_:1;
  NSString* authToken;
}
- (BOOL) hasAuthToken;
@property (readonly, retain) NSString* authToken;

+ (AuthenticateMessage*) defaultInstance;
- (AuthenticateMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthenticateMessage_Builder*) builder;
+ (AuthenticateMessage_Builder*) builder;
+ (AuthenticateMessage_Builder*) builderWithPrototype:(AuthenticateMessage*) prototype;

+ (AuthenticateMessage*) parseFromData:(NSData*) data;
+ (AuthenticateMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthenticateMessage*) parseFromInputStream:(NSInputStream*) input;
+ (AuthenticateMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthenticateMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthenticateMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthenticateMessage_Builder : PBGeneratedMessage_Builder {
@private
  AuthenticateMessage* result;
}

- (AuthenticateMessage*) defaultInstance;

- (AuthenticateMessage_Builder*) clear;
- (AuthenticateMessage_Builder*) clone;

- (AuthenticateMessage*) build;
- (AuthenticateMessage*) buildPartial;

- (AuthenticateMessage_Builder*) mergeFrom:(AuthenticateMessage*) other;
- (AuthenticateMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthenticateMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAuthToken;
- (NSString*) authToken;
- (AuthenticateMessage_Builder*) setAuthToken:(NSString*) value;
- (AuthenticateMessage_Builder*) clearAuthToken;
@end

@interface ClearUserDataMessage : PBGeneratedMessage {
@private
}

+ (ClearUserDataMessage*) defaultInstance;
- (ClearUserDataMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClearUserDataMessage_Builder*) builder;
+ (ClearUserDataMessage_Builder*) builder;
+ (ClearUserDataMessage_Builder*) builderWithPrototype:(ClearUserDataMessage*) prototype;

+ (ClearUserDataMessage*) parseFromData:(NSData*) data;
+ (ClearUserDataMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClearUserDataMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ClearUserDataMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClearUserDataMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClearUserDataMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClearUserDataMessage_Builder : PBGeneratedMessage_Builder {
@private
  ClearUserDataMessage* result;
}

- (ClearUserDataMessage*) defaultInstance;

- (ClearUserDataMessage_Builder*) clear;
- (ClearUserDataMessage_Builder*) clone;

- (ClearUserDataMessage*) build;
- (ClearUserDataMessage*) buildPartial;

- (ClearUserDataMessage_Builder*) mergeFrom:(ClearUserDataMessage*) other;
- (ClearUserDataMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClearUserDataMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClearUserDataResponse : PBGeneratedMessage {
@private
}

+ (ClearUserDataResponse*) defaultInstance;
- (ClearUserDataResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClearUserDataResponse_Builder*) builder;
+ (ClearUserDataResponse_Builder*) builder;
+ (ClearUserDataResponse_Builder*) builderWithPrototype:(ClearUserDataResponse*) prototype;

+ (ClearUserDataResponse*) parseFromData:(NSData*) data;
+ (ClearUserDataResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClearUserDataResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ClearUserDataResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClearUserDataResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClearUserDataResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClearUserDataResponse_Builder : PBGeneratedMessage_Builder {
@private
  ClearUserDataResponse* result;
}

- (ClearUserDataResponse*) defaultInstance;

- (ClearUserDataResponse_Builder*) clear;
- (ClearUserDataResponse_Builder*) clone;

- (ClearUserDataResponse*) build;
- (ClearUserDataResponse*) buildPartial;

- (ClearUserDataResponse_Builder*) mergeFrom:(ClearUserDataResponse*) other;
- (ClearUserDataResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClearUserDataResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientToServerMessage : PBGeneratedMessage {
@private
  BOOL hasSyncProblemDetected_:1;
  BOOL hasProtocolVersion_:1;
  BOOL hasShare_:1;
  BOOL hasStoreBirthday_:1;
  BOOL hasCommit_:1;
  BOOL hasGetUpdates_:1;
  BOOL hasAuthenticate_:1;
  BOOL hasClearUserData_:1;
  BOOL hasDebugInfo_:1;
  BOOL hasMessageContents_:1;
  BOOL syncProblemDetected_:1;
  int32_t protocolVersion;
  NSString* share;
  NSString* storeBirthday;
  CommitMessage* commit;
  GetUpdatesMessage* getUpdates;
  AuthenticateMessage* authenticate;
  ClearUserDataMessage* clearUserData;
  DebugInfo* debugInfo;
  ClientToServerMessage_Contents messageContents;
}
- (BOOL) hasShare;
- (BOOL) hasProtocolVersion;
- (BOOL) hasMessageContents;
- (BOOL) hasCommit;
- (BOOL) hasGetUpdates;
- (BOOL) hasAuthenticate;
- (BOOL) hasClearUserData;
- (BOOL) hasStoreBirthday;
- (BOOL) hasSyncProblemDetected;
- (BOOL) hasDebugInfo;
@property (readonly, retain) NSString* share;
@property (readonly) int32_t protocolVersion;
@property (readonly) ClientToServerMessage_Contents messageContents;
@property (readonly, retain) CommitMessage* commit;
@property (readonly, retain) GetUpdatesMessage* getUpdates;
@property (readonly, retain) AuthenticateMessage* authenticate;
@property (readonly, retain) ClearUserDataMessage* clearUserData;
@property (readonly, retain) NSString* storeBirthday;
- (BOOL) syncProblemDetected;
@property (readonly, retain) DebugInfo* debugInfo;

+ (ClientToServerMessage*) defaultInstance;
- (ClientToServerMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientToServerMessage_Builder*) builder;
+ (ClientToServerMessage_Builder*) builder;
+ (ClientToServerMessage_Builder*) builderWithPrototype:(ClientToServerMessage*) prototype;

+ (ClientToServerMessage*) parseFromData:(NSData*) data;
+ (ClientToServerMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientToServerMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ClientToServerMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientToServerMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientToServerMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientToServerMessage_Builder : PBGeneratedMessage_Builder {
@private
  ClientToServerMessage* result;
}

- (ClientToServerMessage*) defaultInstance;

- (ClientToServerMessage_Builder*) clear;
- (ClientToServerMessage_Builder*) clone;

- (ClientToServerMessage*) build;
- (ClientToServerMessage*) buildPartial;

- (ClientToServerMessage_Builder*) mergeFrom:(ClientToServerMessage*) other;
- (ClientToServerMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientToServerMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasShare;
- (NSString*) share;
- (ClientToServerMessage_Builder*) setShare:(NSString*) value;
- (ClientToServerMessage_Builder*) clearShare;

- (BOOL) hasProtocolVersion;
- (int32_t) protocolVersion;
- (ClientToServerMessage_Builder*) setProtocolVersion:(int32_t) value;
- (ClientToServerMessage_Builder*) clearProtocolVersion;

- (BOOL) hasMessageContents;
- (ClientToServerMessage_Contents) messageContents;
- (ClientToServerMessage_Builder*) setMessageContents:(ClientToServerMessage_Contents) value;
- (ClientToServerMessage_Builder*) clearMessageContents;

- (BOOL) hasCommit;
- (CommitMessage*) commit;
- (ClientToServerMessage_Builder*) setCommit:(CommitMessage*) value;
- (ClientToServerMessage_Builder*) setCommitBuilder:(CommitMessage_Builder*) builderForValue;
- (ClientToServerMessage_Builder*) mergeCommit:(CommitMessage*) value;
- (ClientToServerMessage_Builder*) clearCommit;

- (BOOL) hasGetUpdates;
- (GetUpdatesMessage*) getUpdates;
- (ClientToServerMessage_Builder*) setGetUpdates:(GetUpdatesMessage*) value;
- (ClientToServerMessage_Builder*) setGetUpdatesBuilder:(GetUpdatesMessage_Builder*) builderForValue;
- (ClientToServerMessage_Builder*) mergeGetUpdates:(GetUpdatesMessage*) value;
- (ClientToServerMessage_Builder*) clearGetUpdates;

- (BOOL) hasAuthenticate;
- (AuthenticateMessage*) authenticate;
- (ClientToServerMessage_Builder*) setAuthenticate:(AuthenticateMessage*) value;
- (ClientToServerMessage_Builder*) setAuthenticateBuilder:(AuthenticateMessage_Builder*) builderForValue;
- (ClientToServerMessage_Builder*) mergeAuthenticate:(AuthenticateMessage*) value;
- (ClientToServerMessage_Builder*) clearAuthenticate;

- (BOOL) hasClearUserData;
- (ClearUserDataMessage*) clearUserData;
- (ClientToServerMessage_Builder*) setClearUserData:(ClearUserDataMessage*) value;
- (ClientToServerMessage_Builder*) setClearUserDataBuilder:(ClearUserDataMessage_Builder*) builderForValue;
- (ClientToServerMessage_Builder*) mergeClearUserData:(ClearUserDataMessage*) value;
- (ClientToServerMessage_Builder*) clearClearUserData;

- (BOOL) hasStoreBirthday;
- (NSString*) storeBirthday;
- (ClientToServerMessage_Builder*) setStoreBirthday:(NSString*) value;
- (ClientToServerMessage_Builder*) clearStoreBirthday;

- (BOOL) hasSyncProblemDetected;
- (BOOL) syncProblemDetected;
- (ClientToServerMessage_Builder*) setSyncProblemDetected:(BOOL) value;
- (ClientToServerMessage_Builder*) clearSyncProblemDetected;

- (BOOL) hasDebugInfo;
- (DebugInfo*) debugInfo;
- (ClientToServerMessage_Builder*) setDebugInfo:(DebugInfo*) value;
- (ClientToServerMessage_Builder*) setDebugInfoBuilder:(DebugInfo_Builder*) builderForValue;
- (ClientToServerMessage_Builder*) mergeDebugInfo:(DebugInfo*) value;
- (ClientToServerMessage_Builder*) clearDebugInfo;
@end

@interface CommitResponse : PBGeneratedMessage {
@private
  NSMutableArray* mutableEntryResponseList;
}
- (NSArray*) entryResponseList;
- (CommitResponse_EntryResponse*) entryResponseAtIndex:(int32_t) index;

+ (CommitResponse*) defaultInstance;
- (CommitResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CommitResponse_Builder*) builder;
+ (CommitResponse_Builder*) builder;
+ (CommitResponse_Builder*) builderWithPrototype:(CommitResponse*) prototype;

+ (CommitResponse*) parseFromData:(NSData*) data;
+ (CommitResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommitResponse*) parseFromInputStream:(NSInputStream*) input;
+ (CommitResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommitResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CommitResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CommitResponse_EntryResponse : PBGeneratedMessage {
@private
  BOOL hasPositionInParent_:1;
  BOOL hasVersion_:1;
  BOOL hasMtime_:1;
  BOOL hasIdString_:1;
  BOOL hasParentIdString_:1;
  BOOL hasName_:1;
  BOOL hasNonUniqueName_:1;
  BOOL hasErrorMessage_:1;
  BOOL hasResponseType_:1;
  int64_t positionInParent;
  int64_t version;
  int64_t mtime;
  NSString* idString;
  NSString* parentIdString;
  NSString* name;
  NSString* nonUniqueName;
  NSString* errorMessage;
  CommitResponse_ResponseType responseType;
}
- (BOOL) hasResponseType;
- (BOOL) hasIdString;
- (BOOL) hasParentIdString;
- (BOOL) hasPositionInParent;
- (BOOL) hasVersion;
- (BOOL) hasName;
- (BOOL) hasNonUniqueName;
- (BOOL) hasErrorMessage;
- (BOOL) hasMtime;
@property (readonly) CommitResponse_ResponseType responseType;
@property (readonly, retain) NSString* idString;
@property (readonly, retain) NSString* parentIdString;
@property (readonly) int64_t positionInParent;
@property (readonly) int64_t version;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* nonUniqueName;
@property (readonly, retain) NSString* errorMessage;
@property (readonly) int64_t mtime;

+ (CommitResponse_EntryResponse*) defaultInstance;
- (CommitResponse_EntryResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CommitResponse_EntryResponse_Builder*) builder;
+ (CommitResponse_EntryResponse_Builder*) builder;
+ (CommitResponse_EntryResponse_Builder*) builderWithPrototype:(CommitResponse_EntryResponse*) prototype;

+ (CommitResponse_EntryResponse*) parseFromData:(NSData*) data;
+ (CommitResponse_EntryResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommitResponse_EntryResponse*) parseFromInputStream:(NSInputStream*) input;
+ (CommitResponse_EntryResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommitResponse_EntryResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CommitResponse_EntryResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CommitResponse_EntryResponse_Builder : PBGeneratedMessage_Builder {
@private
  CommitResponse_EntryResponse* result;
}

- (CommitResponse_EntryResponse*) defaultInstance;

- (CommitResponse_EntryResponse_Builder*) clear;
- (CommitResponse_EntryResponse_Builder*) clone;

- (CommitResponse_EntryResponse*) build;
- (CommitResponse_EntryResponse*) buildPartial;

- (CommitResponse_EntryResponse_Builder*) mergeFrom:(CommitResponse_EntryResponse*) other;
- (CommitResponse_EntryResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CommitResponse_EntryResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResponseType;
- (CommitResponse_ResponseType) responseType;
- (CommitResponse_EntryResponse_Builder*) setResponseType:(CommitResponse_ResponseType) value;
- (CommitResponse_EntryResponse_Builder*) clearResponseType;

- (BOOL) hasIdString;
- (NSString*) idString;
- (CommitResponse_EntryResponse_Builder*) setIdString:(NSString*) value;
- (CommitResponse_EntryResponse_Builder*) clearIdString;

- (BOOL) hasParentIdString;
- (NSString*) parentIdString;
- (CommitResponse_EntryResponse_Builder*) setParentIdString:(NSString*) value;
- (CommitResponse_EntryResponse_Builder*) clearParentIdString;

- (BOOL) hasPositionInParent;
- (int64_t) positionInParent;
- (CommitResponse_EntryResponse_Builder*) setPositionInParent:(int64_t) value;
- (CommitResponse_EntryResponse_Builder*) clearPositionInParent;

- (BOOL) hasVersion;
- (int64_t) version;
- (CommitResponse_EntryResponse_Builder*) setVersion:(int64_t) value;
- (CommitResponse_EntryResponse_Builder*) clearVersion;

- (BOOL) hasName;
- (NSString*) name;
- (CommitResponse_EntryResponse_Builder*) setName:(NSString*) value;
- (CommitResponse_EntryResponse_Builder*) clearName;

- (BOOL) hasNonUniqueName;
- (NSString*) nonUniqueName;
- (CommitResponse_EntryResponse_Builder*) setNonUniqueName:(NSString*) value;
- (CommitResponse_EntryResponse_Builder*) clearNonUniqueName;

- (BOOL) hasErrorMessage;
- (NSString*) errorMessage;
- (CommitResponse_EntryResponse_Builder*) setErrorMessage:(NSString*) value;
- (CommitResponse_EntryResponse_Builder*) clearErrorMessage;

- (BOOL) hasMtime;
- (int64_t) mtime;
- (CommitResponse_EntryResponse_Builder*) setMtime:(int64_t) value;
- (CommitResponse_EntryResponse_Builder*) clearMtime;
@end

@interface CommitResponse_Builder : PBGeneratedMessage_Builder {
@private
  CommitResponse* result;
}

- (CommitResponse*) defaultInstance;

- (CommitResponse_Builder*) clear;
- (CommitResponse_Builder*) clone;

- (CommitResponse*) build;
- (CommitResponse*) buildPartial;

- (CommitResponse_Builder*) mergeFrom:(CommitResponse*) other;
- (CommitResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CommitResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) entryResponseList;
- (CommitResponse_EntryResponse*) entryResponseAtIndex:(int32_t) index;
- (CommitResponse_Builder*) replaceEntryResponseAtIndex:(int32_t) index with:(CommitResponse_EntryResponse*) value;
- (CommitResponse_Builder*) addEntryResponse:(CommitResponse_EntryResponse*) value;
- (CommitResponse_Builder*) addAllEntryResponse:(NSArray*) values;
- (CommitResponse_Builder*) clearEntryResponseList;
@end

@interface GetUpdatesResponse : PBGeneratedMessage {
@private
  BOOL hasNewTimestamp_:1;
  BOOL hasDeprecatedNewestTimestamp_:1;
  BOOL hasChangesRemaining_:1;
  int64_t newTimestamp;
  int64_t deprecatedNewestTimestamp;
  int64_t changesRemaining;
  NSMutableArray* mutableEntriesList;
  NSMutableArray* mutableNewProgressMarkerList;
}
- (BOOL) hasNewTimestamp;
- (BOOL) hasDeprecatedNewestTimestamp;
- (BOOL) hasChangesRemaining;
@property (readonly) int64_t newTimestamp;
@property (readonly) int64_t deprecatedNewestTimestamp;
@property (readonly) int64_t changesRemaining;
- (NSArray*) entriesList;
- (SyncEntity*) entriesAtIndex:(int32_t) index;
- (NSArray*) newProgressMarkerList;
- (DataTypeProgressMarker*) newProgressMarkerAtIndex:(int32_t) index;

+ (GetUpdatesResponse*) defaultInstance;
- (GetUpdatesResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetUpdatesResponse_Builder*) builder;
+ (GetUpdatesResponse_Builder*) builder;
+ (GetUpdatesResponse_Builder*) builderWithPrototype:(GetUpdatesResponse*) prototype;

+ (GetUpdatesResponse*) parseFromData:(NSData*) data;
+ (GetUpdatesResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesResponse*) parseFromInputStream:(NSInputStream*) input;
+ (GetUpdatesResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetUpdatesResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetUpdatesResponse_Builder : PBGeneratedMessage_Builder {
@private
  GetUpdatesResponse* result;
}

- (GetUpdatesResponse*) defaultInstance;

- (GetUpdatesResponse_Builder*) clear;
- (GetUpdatesResponse_Builder*) clone;

- (GetUpdatesResponse*) build;
- (GetUpdatesResponse*) buildPartial;

- (GetUpdatesResponse_Builder*) mergeFrom:(GetUpdatesResponse*) other;
- (GetUpdatesResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetUpdatesResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) entriesList;
- (SyncEntity*) entriesAtIndex:(int32_t) index;
- (GetUpdatesResponse_Builder*) replaceEntriesAtIndex:(int32_t) index with:(SyncEntity*) value;
- (GetUpdatesResponse_Builder*) addEntries:(SyncEntity*) value;
- (GetUpdatesResponse_Builder*) addAllEntries:(NSArray*) values;
- (GetUpdatesResponse_Builder*) clearEntriesList;

- (BOOL) hasNewTimestamp;
- (int64_t) newTimestamp;
- (GetUpdatesResponse_Builder*) setNewTimestamp:(int64_t) value;
- (GetUpdatesResponse_Builder*) clearNewTimestamp;

- (BOOL) hasDeprecatedNewestTimestamp;
- (int64_t) deprecatedNewestTimestamp;
- (GetUpdatesResponse_Builder*) setDeprecatedNewestTimestamp:(int64_t) value;
- (GetUpdatesResponse_Builder*) clearDeprecatedNewestTimestamp;

- (BOOL) hasChangesRemaining;
- (int64_t) changesRemaining;
- (GetUpdatesResponse_Builder*) setChangesRemaining:(int64_t) value;
- (GetUpdatesResponse_Builder*) clearChangesRemaining;

- (NSArray*) newProgressMarkerList;
- (DataTypeProgressMarker*) newProgressMarkerAtIndex:(int32_t) index;
- (GetUpdatesResponse_Builder*) replaceNewProgressMarkerAtIndex:(int32_t) index with:(DataTypeProgressMarker*) value;
- (GetUpdatesResponse_Builder*) addNewProgressMarker:(DataTypeProgressMarker*) value;
- (GetUpdatesResponse_Builder*) addAllNewProgressMarker:(NSArray*) values;
- (GetUpdatesResponse_Builder*) clearNewProgressMarkerList;
@end

@interface GetUpdatesMetadataResponse : PBGeneratedMessage {
@private
  BOOL hasChangesRemaining_:1;
  int64_t changesRemaining;
  NSMutableArray* mutableNewProgressMarkerList;
}
- (BOOL) hasChangesRemaining;
@property (readonly) int64_t changesRemaining;
- (NSArray*) newProgressMarkerList;
- (DataTypeProgressMarker*) newProgressMarkerAtIndex:(int32_t) index;

+ (GetUpdatesMetadataResponse*) defaultInstance;
- (GetUpdatesMetadataResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetUpdatesMetadataResponse_Builder*) builder;
+ (GetUpdatesMetadataResponse_Builder*) builder;
+ (GetUpdatesMetadataResponse_Builder*) builderWithPrototype:(GetUpdatesMetadataResponse*) prototype;

+ (GetUpdatesMetadataResponse*) parseFromData:(NSData*) data;
+ (GetUpdatesMetadataResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesMetadataResponse*) parseFromInputStream:(NSInputStream*) input;
+ (GetUpdatesMetadataResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesMetadataResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetUpdatesMetadataResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetUpdatesMetadataResponse_Builder : PBGeneratedMessage_Builder {
@private
  GetUpdatesMetadataResponse* result;
}

- (GetUpdatesMetadataResponse*) defaultInstance;

- (GetUpdatesMetadataResponse_Builder*) clear;
- (GetUpdatesMetadataResponse_Builder*) clone;

- (GetUpdatesMetadataResponse*) build;
- (GetUpdatesMetadataResponse*) buildPartial;

- (GetUpdatesMetadataResponse_Builder*) mergeFrom:(GetUpdatesMetadataResponse*) other;
- (GetUpdatesMetadataResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetUpdatesMetadataResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasChangesRemaining;
- (int64_t) changesRemaining;
- (GetUpdatesMetadataResponse_Builder*) setChangesRemaining:(int64_t) value;
- (GetUpdatesMetadataResponse_Builder*) clearChangesRemaining;

- (NSArray*) newProgressMarkerList;
- (DataTypeProgressMarker*) newProgressMarkerAtIndex:(int32_t) index;
- (GetUpdatesMetadataResponse_Builder*) replaceNewProgressMarkerAtIndex:(int32_t) index with:(DataTypeProgressMarker*) value;
- (GetUpdatesMetadataResponse_Builder*) addNewProgressMarker:(DataTypeProgressMarker*) value;
- (GetUpdatesMetadataResponse_Builder*) addAllNewProgressMarker:(NSArray*) values;
- (GetUpdatesMetadataResponse_Builder*) clearNewProgressMarkerList;
@end

@interface GetUpdatesStreamingResponse : PBGeneratedMessage {
@private
  NSMutableArray* mutableEntriesList;
}
- (NSArray*) entriesList;
- (SyncEntity*) entriesAtIndex:(int32_t) index;

+ (GetUpdatesStreamingResponse*) defaultInstance;
- (GetUpdatesStreamingResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetUpdatesStreamingResponse_Builder*) builder;
+ (GetUpdatesStreamingResponse_Builder*) builder;
+ (GetUpdatesStreamingResponse_Builder*) builderWithPrototype:(GetUpdatesStreamingResponse*) prototype;

+ (GetUpdatesStreamingResponse*) parseFromData:(NSData*) data;
+ (GetUpdatesStreamingResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesStreamingResponse*) parseFromInputStream:(NSInputStream*) input;
+ (GetUpdatesStreamingResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetUpdatesStreamingResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetUpdatesStreamingResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetUpdatesStreamingResponse_Builder : PBGeneratedMessage_Builder {
@private
  GetUpdatesStreamingResponse* result;
}

- (GetUpdatesStreamingResponse*) defaultInstance;

- (GetUpdatesStreamingResponse_Builder*) clear;
- (GetUpdatesStreamingResponse_Builder*) clone;

- (GetUpdatesStreamingResponse*) build;
- (GetUpdatesStreamingResponse*) buildPartial;

- (GetUpdatesStreamingResponse_Builder*) mergeFrom:(GetUpdatesStreamingResponse*) other;
- (GetUpdatesStreamingResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetUpdatesStreamingResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) entriesList;
- (SyncEntity*) entriesAtIndex:(int32_t) index;
- (GetUpdatesStreamingResponse_Builder*) replaceEntriesAtIndex:(int32_t) index with:(SyncEntity*) value;
- (GetUpdatesStreamingResponse_Builder*) addEntries:(SyncEntity*) value;
- (GetUpdatesStreamingResponse_Builder*) addAllEntries:(NSArray*) values;
- (GetUpdatesStreamingResponse_Builder*) clearEntriesList;
@end

@interface UserIdentification : PBGeneratedMessage {
@private
  BOOL hasEmail_:1;
  BOOL hasDisplayName_:1;
  BOOL hasObfuscatedId_:1;
  NSString* email;
  NSString* displayName;
  NSString* obfuscatedId;
}
- (BOOL) hasEmail;
- (BOOL) hasDisplayName;
- (BOOL) hasObfuscatedId;
@property (readonly, retain) NSString* email;
@property (readonly, retain) NSString* displayName;
@property (readonly, retain) NSString* obfuscatedId;

+ (UserIdentification*) defaultInstance;
- (UserIdentification*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserIdentification_Builder*) builder;
+ (UserIdentification_Builder*) builder;
+ (UserIdentification_Builder*) builderWithPrototype:(UserIdentification*) prototype;

+ (UserIdentification*) parseFromData:(NSData*) data;
+ (UserIdentification*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserIdentification*) parseFromInputStream:(NSInputStream*) input;
+ (UserIdentification*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserIdentification*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserIdentification*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserIdentification_Builder : PBGeneratedMessage_Builder {
@private
  UserIdentification* result;
}

- (UserIdentification*) defaultInstance;

- (UserIdentification_Builder*) clear;
- (UserIdentification_Builder*) clone;

- (UserIdentification*) build;
- (UserIdentification*) buildPartial;

- (UserIdentification_Builder*) mergeFrom:(UserIdentification*) other;
- (UserIdentification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserIdentification_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEmail;
- (NSString*) email;
- (UserIdentification_Builder*) setEmail:(NSString*) value;
- (UserIdentification_Builder*) clearEmail;

- (BOOL) hasDisplayName;
- (NSString*) displayName;
- (UserIdentification_Builder*) setDisplayName:(NSString*) value;
- (UserIdentification_Builder*) clearDisplayName;

- (BOOL) hasObfuscatedId;
- (NSString*) obfuscatedId;
- (UserIdentification_Builder*) setObfuscatedId:(NSString*) value;
- (UserIdentification_Builder*) clearObfuscatedId;
@end

@interface AuthenticateResponse : PBGeneratedMessage {
@private
  BOOL hasUser_:1;
  UserIdentification* user;
}
- (BOOL) hasUser;
@property (readonly, retain) UserIdentification* user;

+ (AuthenticateResponse*) defaultInstance;
- (AuthenticateResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthenticateResponse_Builder*) builder;
+ (AuthenticateResponse_Builder*) builder;
+ (AuthenticateResponse_Builder*) builderWithPrototype:(AuthenticateResponse*) prototype;

+ (AuthenticateResponse*) parseFromData:(NSData*) data;
+ (AuthenticateResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthenticateResponse*) parseFromInputStream:(NSInputStream*) input;
+ (AuthenticateResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthenticateResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthenticateResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthenticateResponse_Builder : PBGeneratedMessage_Builder {
@private
  AuthenticateResponse* result;
}

- (AuthenticateResponse*) defaultInstance;

- (AuthenticateResponse_Builder*) clear;
- (AuthenticateResponse_Builder*) clone;

- (AuthenticateResponse*) build;
- (AuthenticateResponse*) buildPartial;

- (AuthenticateResponse_Builder*) mergeFrom:(AuthenticateResponse*) other;
- (AuthenticateResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthenticateResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUser;
- (UserIdentification*) user;
- (AuthenticateResponse_Builder*) setUser:(UserIdentification*) value;
- (AuthenticateResponse_Builder*) setUserBuilder:(UserIdentification_Builder*) builderForValue;
- (AuthenticateResponse_Builder*) mergeUser:(UserIdentification*) value;
- (AuthenticateResponse_Builder*) clearUser;
@end

@interface ThrottleParameters : PBGeneratedMessage {
@private
  BOOL hasTargetUtilization_:1;
  BOOL hasMeasureIntervalMax_:1;
  BOOL hasMeasureIntervalMin_:1;
  BOOL hasObservationWindow_:1;
  BOOL hasMinMeasurePayloadSize_:1;
  Float64 targetUtilization;
  Float64 measureIntervalMax;
  Float64 measureIntervalMin;
  Float64 observationWindow;
  int32_t minMeasurePayloadSize;
}
- (BOOL) hasMinMeasurePayloadSize;
- (BOOL) hasTargetUtilization;
- (BOOL) hasMeasureIntervalMax;
- (BOOL) hasMeasureIntervalMin;
- (BOOL) hasObservationWindow;
@property (readonly) int32_t minMeasurePayloadSize;
@property (readonly) Float64 targetUtilization;
@property (readonly) Float64 measureIntervalMax;
@property (readonly) Float64 measureIntervalMin;
@property (readonly) Float64 observationWindow;

+ (ThrottleParameters*) defaultInstance;
- (ThrottleParameters*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ThrottleParameters_Builder*) builder;
+ (ThrottleParameters_Builder*) builder;
+ (ThrottleParameters_Builder*) builderWithPrototype:(ThrottleParameters*) prototype;

+ (ThrottleParameters*) parseFromData:(NSData*) data;
+ (ThrottleParameters*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ThrottleParameters*) parseFromInputStream:(NSInputStream*) input;
+ (ThrottleParameters*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ThrottleParameters*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ThrottleParameters*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ThrottleParameters_Builder : PBGeneratedMessage_Builder {
@private
  ThrottleParameters* result;
}

- (ThrottleParameters*) defaultInstance;

- (ThrottleParameters_Builder*) clear;
- (ThrottleParameters_Builder*) clone;

- (ThrottleParameters*) build;
- (ThrottleParameters*) buildPartial;

- (ThrottleParameters_Builder*) mergeFrom:(ThrottleParameters*) other;
- (ThrottleParameters_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ThrottleParameters_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMinMeasurePayloadSize;
- (int32_t) minMeasurePayloadSize;
- (ThrottleParameters_Builder*) setMinMeasurePayloadSize:(int32_t) value;
- (ThrottleParameters_Builder*) clearMinMeasurePayloadSize;

- (BOOL) hasTargetUtilization;
- (Float64) targetUtilization;
- (ThrottleParameters_Builder*) setTargetUtilization:(Float64) value;
- (ThrottleParameters_Builder*) clearTargetUtilization;

- (BOOL) hasMeasureIntervalMax;
- (Float64) measureIntervalMax;
- (ThrottleParameters_Builder*) setMeasureIntervalMax:(Float64) value;
- (ThrottleParameters_Builder*) clearMeasureIntervalMax;

- (BOOL) hasMeasureIntervalMin;
- (Float64) measureIntervalMin;
- (ThrottleParameters_Builder*) setMeasureIntervalMin:(Float64) value;
- (ThrottleParameters_Builder*) clearMeasureIntervalMin;

- (BOOL) hasObservationWindow;
- (Float64) observationWindow;
- (ThrottleParameters_Builder*) setObservationWindow:(Float64) value;
- (ThrottleParameters_Builder*) clearObservationWindow;
@end

@interface ClientToServerResponse : PBGeneratedMessage {
@private
  BOOL hasErrorMessage_:1;
  BOOL hasStoreBirthday_:1;
  BOOL hasCommit_:1;
  BOOL hasGetUpdates_:1;
  BOOL hasAuthenticate_:1;
  BOOL hasClearUserData_:1;
  BOOL hasStreamMetadata_:1;
  BOOL hasStreamData_:1;
  BOOL hasError_:1;
  BOOL hasClientCommand_:1;
  BOOL hasProfilingData_:1;
  BOOL hasErrorCode_:1;
  NSString* errorMessage;
  NSString* storeBirthday;
  CommitResponse* commit;
  GetUpdatesResponse* getUpdates;
  AuthenticateResponse* authenticate;
  ClearUserDataResponse* clearUserData;
  GetUpdatesMetadataResponse* streamMetadata;
  GetUpdatesStreamingResponse* streamData;
  ClientToServerResponse_Error* error;
  ClientCommand* clientCommand;
  ProfilingData* profilingData;
  SyncEnums_ErrorType errorCode;
  NSMutableArray* mutableMigratedDataTypeIdList;
}
- (BOOL) hasCommit;
- (BOOL) hasGetUpdates;
- (BOOL) hasAuthenticate;
- (BOOL) hasClearUserData;
- (BOOL) hasStreamMetadata;
- (BOOL) hasStreamData;
- (BOOL) hasError;
- (BOOL) hasErrorCode;
- (BOOL) hasErrorMessage;
- (BOOL) hasStoreBirthday;
- (BOOL) hasClientCommand;
- (BOOL) hasProfilingData;
@property (readonly, retain) CommitResponse* commit;
@property (readonly, retain) GetUpdatesResponse* getUpdates;
@property (readonly, retain) AuthenticateResponse* authenticate;
@property (readonly, retain) ClearUserDataResponse* clearUserData;
@property (readonly, retain) GetUpdatesMetadataResponse* streamMetadata;
@property (readonly, retain) GetUpdatesStreamingResponse* streamData;
@property (readonly, retain) ClientToServerResponse_Error* error;
@property (readonly) SyncEnums_ErrorType errorCode;
@property (readonly, retain) NSString* errorMessage;
@property (readonly, retain) NSString* storeBirthday;
@property (readonly, retain) ClientCommand* clientCommand;
@property (readonly, retain) ProfilingData* profilingData;
- (NSArray*) migratedDataTypeIdList;
- (int32_t) migratedDataTypeIdAtIndex:(int32_t) index;

+ (ClientToServerResponse*) defaultInstance;
- (ClientToServerResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientToServerResponse_Builder*) builder;
+ (ClientToServerResponse_Builder*) builder;
+ (ClientToServerResponse_Builder*) builderWithPrototype:(ClientToServerResponse*) prototype;

+ (ClientToServerResponse*) parseFromData:(NSData*) data;
+ (ClientToServerResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientToServerResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ClientToServerResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientToServerResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientToServerResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientToServerResponse_Error : PBGeneratedMessage {
@private
  BOOL hasErrorDescription_:1;
  BOOL hasUrl_:1;
  BOOL hasErrorType_:1;
  BOOL hasAction_:1;
  NSString* errorDescription;
  NSString* url;
  SyncEnums_ErrorType errorType;
  SyncEnums_Action action;
  NSMutableArray* mutableErrorDataTypeIdsList;
}
- (BOOL) hasErrorType;
- (BOOL) hasErrorDescription;
- (BOOL) hasUrl;
- (BOOL) hasAction;
@property (readonly) SyncEnums_ErrorType errorType;
@property (readonly, retain) NSString* errorDescription;
@property (readonly, retain) NSString* url;
@property (readonly) SyncEnums_Action action;
- (NSArray*) errorDataTypeIdsList;
- (int32_t) errorDataTypeIdsAtIndex:(int32_t) index;

+ (ClientToServerResponse_Error*) defaultInstance;
- (ClientToServerResponse_Error*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClientToServerResponse_Error_Builder*) builder;
+ (ClientToServerResponse_Error_Builder*) builder;
+ (ClientToServerResponse_Error_Builder*) builderWithPrototype:(ClientToServerResponse_Error*) prototype;

+ (ClientToServerResponse_Error*) parseFromData:(NSData*) data;
+ (ClientToServerResponse_Error*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientToServerResponse_Error*) parseFromInputStream:(NSInputStream*) input;
+ (ClientToServerResponse_Error*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClientToServerResponse_Error*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClientToServerResponse_Error*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientToServerResponse_Error_Builder : PBGeneratedMessage_Builder {
@private
  ClientToServerResponse_Error* result;
}

- (ClientToServerResponse_Error*) defaultInstance;

- (ClientToServerResponse_Error_Builder*) clear;
- (ClientToServerResponse_Error_Builder*) clone;

- (ClientToServerResponse_Error*) build;
- (ClientToServerResponse_Error*) buildPartial;

- (ClientToServerResponse_Error_Builder*) mergeFrom:(ClientToServerResponse_Error*) other;
- (ClientToServerResponse_Error_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientToServerResponse_Error_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasErrorType;
- (SyncEnums_ErrorType) errorType;
- (ClientToServerResponse_Error_Builder*) setErrorType:(SyncEnums_ErrorType) value;
- (ClientToServerResponse_Error_Builder*) clearErrorType;

- (BOOL) hasErrorDescription;
- (NSString*) errorDescription;
- (ClientToServerResponse_Error_Builder*) setErrorDescription:(NSString*) value;
- (ClientToServerResponse_Error_Builder*) clearErrorDescription;

- (BOOL) hasUrl;
- (NSString*) url;
- (ClientToServerResponse_Error_Builder*) setUrl:(NSString*) value;
- (ClientToServerResponse_Error_Builder*) clearUrl;

- (BOOL) hasAction;
- (SyncEnums_Action) action;
- (ClientToServerResponse_Error_Builder*) setAction:(SyncEnums_Action) value;
- (ClientToServerResponse_Error_Builder*) clearAction;

- (NSArray*) errorDataTypeIdsList;
- (int32_t) errorDataTypeIdsAtIndex:(int32_t) index;
- (ClientToServerResponse_Error_Builder*) replaceErrorDataTypeIdsAtIndex:(int32_t) index with:(int32_t) value;
- (ClientToServerResponse_Error_Builder*) addErrorDataTypeIds:(int32_t) value;
- (ClientToServerResponse_Error_Builder*) addAllErrorDataTypeIds:(NSArray*) values;
- (ClientToServerResponse_Error_Builder*) clearErrorDataTypeIdsList;
@end

@interface ClientToServerResponse_Builder : PBGeneratedMessage_Builder {
@private
  ClientToServerResponse* result;
}

- (ClientToServerResponse*) defaultInstance;

- (ClientToServerResponse_Builder*) clear;
- (ClientToServerResponse_Builder*) clone;

- (ClientToServerResponse*) build;
- (ClientToServerResponse*) buildPartial;

- (ClientToServerResponse_Builder*) mergeFrom:(ClientToServerResponse*) other;
- (ClientToServerResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClientToServerResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCommit;
- (CommitResponse*) commit;
- (ClientToServerResponse_Builder*) setCommit:(CommitResponse*) value;
- (ClientToServerResponse_Builder*) setCommitBuilder:(CommitResponse_Builder*) builderForValue;
- (ClientToServerResponse_Builder*) mergeCommit:(CommitResponse*) value;
- (ClientToServerResponse_Builder*) clearCommit;

- (BOOL) hasGetUpdates;
- (GetUpdatesResponse*) getUpdates;
- (ClientToServerResponse_Builder*) setGetUpdates:(GetUpdatesResponse*) value;
- (ClientToServerResponse_Builder*) setGetUpdatesBuilder:(GetUpdatesResponse_Builder*) builderForValue;
- (ClientToServerResponse_Builder*) mergeGetUpdates:(GetUpdatesResponse*) value;
- (ClientToServerResponse_Builder*) clearGetUpdates;

- (BOOL) hasAuthenticate;
- (AuthenticateResponse*) authenticate;
- (ClientToServerResponse_Builder*) setAuthenticate:(AuthenticateResponse*) value;
- (ClientToServerResponse_Builder*) setAuthenticateBuilder:(AuthenticateResponse_Builder*) builderForValue;
- (ClientToServerResponse_Builder*) mergeAuthenticate:(AuthenticateResponse*) value;
- (ClientToServerResponse_Builder*) clearAuthenticate;

- (BOOL) hasClearUserData;
- (ClearUserDataResponse*) clearUserData;
- (ClientToServerResponse_Builder*) setClearUserData:(ClearUserDataResponse*) value;
- (ClientToServerResponse_Builder*) setClearUserDataBuilder:(ClearUserDataResponse_Builder*) builderForValue;
- (ClientToServerResponse_Builder*) mergeClearUserData:(ClearUserDataResponse*) value;
- (ClientToServerResponse_Builder*) clearClearUserData;

- (BOOL) hasStreamMetadata;
- (GetUpdatesMetadataResponse*) streamMetadata;
- (ClientToServerResponse_Builder*) setStreamMetadata:(GetUpdatesMetadataResponse*) value;
- (ClientToServerResponse_Builder*) setStreamMetadataBuilder:(GetUpdatesMetadataResponse_Builder*) builderForValue;
- (ClientToServerResponse_Builder*) mergeStreamMetadata:(GetUpdatesMetadataResponse*) value;
- (ClientToServerResponse_Builder*) clearStreamMetadata;

- (BOOL) hasStreamData;
- (GetUpdatesStreamingResponse*) streamData;
- (ClientToServerResponse_Builder*) setStreamData:(GetUpdatesStreamingResponse*) value;
- (ClientToServerResponse_Builder*) setStreamDataBuilder:(GetUpdatesStreamingResponse_Builder*) builderForValue;
- (ClientToServerResponse_Builder*) mergeStreamData:(GetUpdatesStreamingResponse*) value;
- (ClientToServerResponse_Builder*) clearStreamData;

- (BOOL) hasError;
- (ClientToServerResponse_Error*) error;
- (ClientToServerResponse_Builder*) setError:(ClientToServerResponse_Error*) value;
- (ClientToServerResponse_Builder*) setErrorBuilder:(ClientToServerResponse_Error_Builder*) builderForValue;
- (ClientToServerResponse_Builder*) mergeError:(ClientToServerResponse_Error*) value;
- (ClientToServerResponse_Builder*) clearError;

- (BOOL) hasErrorCode;
- (SyncEnums_ErrorType) errorCode;
- (ClientToServerResponse_Builder*) setErrorCode:(SyncEnums_ErrorType) value;
- (ClientToServerResponse_Builder*) clearErrorCode;

- (BOOL) hasErrorMessage;
- (NSString*) errorMessage;
- (ClientToServerResponse_Builder*) setErrorMessage:(NSString*) value;
- (ClientToServerResponse_Builder*) clearErrorMessage;

- (BOOL) hasStoreBirthday;
- (NSString*) storeBirthday;
- (ClientToServerResponse_Builder*) setStoreBirthday:(NSString*) value;
- (ClientToServerResponse_Builder*) clearStoreBirthday;

- (BOOL) hasClientCommand;
- (ClientCommand*) clientCommand;
- (ClientToServerResponse_Builder*) setClientCommand:(ClientCommand*) value;
- (ClientToServerResponse_Builder*) setClientCommandBuilder:(ClientCommand_Builder*) builderForValue;
- (ClientToServerResponse_Builder*) mergeClientCommand:(ClientCommand*) value;
- (ClientToServerResponse_Builder*) clearClientCommand;

- (BOOL) hasProfilingData;
- (ProfilingData*) profilingData;
- (ClientToServerResponse_Builder*) setProfilingData:(ProfilingData*) value;
- (ClientToServerResponse_Builder*) setProfilingDataBuilder:(ProfilingData_Builder*) builderForValue;
- (ClientToServerResponse_Builder*) mergeProfilingData:(ProfilingData*) value;
- (ClientToServerResponse_Builder*) clearProfilingData;

- (NSArray*) migratedDataTypeIdList;
- (int32_t) migratedDataTypeIdAtIndex:(int32_t) index;
- (ClientToServerResponse_Builder*) replaceMigratedDataTypeIdAtIndex:(int32_t) index with:(int32_t) value;
- (ClientToServerResponse_Builder*) addMigratedDataTypeId:(int32_t) value;
- (ClientToServerResponse_Builder*) addAllMigratedDataTypeId:(NSArray*) values;
- (ClientToServerResponse_Builder*) clearMigratedDataTypeIdList;
@end

