// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class SyncEnums;
@class SyncEnums_Builder;
typedef enum {
  SyncEnums_EventTypeAuthError = 1,
  SyncEnums_EventTypeUpdatedToken = 2,
  SyncEnums_EventTypePassphraseRequired = 3,
  SyncEnums_EventTypePassphraseAccepted = 4,
  SyncEnums_EventTypeInitializationComplete = 5,
  SyncEnums_EventTypeStopSyncingPermanently = 6,
  SyncEnums_EventTypeEncryptedTypesChanged = 9,
  SyncEnums_EventTypeEncryptionComplete = 7,
  SyncEnums_EventTypeActionableError = 8,
} SyncEnums_EventType;

BOOL SyncEnums_EventTypeIsValidValue(SyncEnums_EventType value);

typedef enum {
  SyncEnums_ErrorTypeSuccess = 0,
  SyncEnums_ErrorTypeAccessDenied = 1,
  SyncEnums_ErrorTypeNotMyBirthday = 2,
  SyncEnums_ErrorTypeThrottled = 3,
  SyncEnums_ErrorTypeAuthExpired = 4,
  SyncEnums_ErrorTypeUserNotActivated = 5,
  SyncEnums_ErrorTypeAuthInvalid = 6,
  SyncEnums_ErrorTypeClearPending = 7,
  SyncEnums_ErrorTypeTransientError = 8,
  SyncEnums_ErrorTypeMigrationDone = 9,
  SyncEnums_ErrorTypeUnknown = 100,
} SyncEnums_ErrorType;

BOOL SyncEnums_ErrorTypeIsValidValue(SyncEnums_ErrorType value);

typedef enum {
  SyncEnums_ActionUpgradeClient = 0,
  SyncEnums_ActionClearUserDataAndResync = 1,
  SyncEnums_ActionEnableSyncOnAccount = 2,
  SyncEnums_ActionStopAndRestartSync = 3,
  SyncEnums_ActionDisableSyncOnClient = 4,
  SyncEnums_ActionUnknownAction = 5,
} SyncEnums_Action;

BOOL SyncEnums_ActionIsValidValue(SyncEnums_Action value);


@interface SyncEnumsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface SyncEnums : PBGeneratedMessage {
@private
}

+ (SyncEnums*) defaultInstance;
- (SyncEnums*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SyncEnums_Builder*) builder;
+ (SyncEnums_Builder*) builder;
+ (SyncEnums_Builder*) builderWithPrototype:(SyncEnums*) prototype;

+ (SyncEnums*) parseFromData:(NSData*) data;
+ (SyncEnums*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncEnums*) parseFromInputStream:(NSInputStream*) input;
+ (SyncEnums*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SyncEnums*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SyncEnums*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SyncEnums_Builder : PBGeneratedMessage_Builder {
@private
  SyncEnums* result;
}

- (SyncEnums*) defaultInstance;

- (SyncEnums_Builder*) clear;
- (SyncEnums_Builder*) clone;

- (SyncEnums*) build;
- (SyncEnums*) buildPartial;

- (SyncEnums_Builder*) mergeFrom:(SyncEnums*) other;
- (SyncEnums_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SyncEnums_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

