// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ThemeSpecifics;
@class ThemeSpecifics_Builder;

@interface ThemeSpecificsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ThemeSpecifics : PBGeneratedMessage {
@private
  BOOL hasUseCustomTheme_:1;
  BOOL hasUseSystemThemeByDefault_:1;
  BOOL hasCustomThemeName_:1;
  BOOL hasCustomThemeId_:1;
  BOOL hasCustomThemeUpdateUrl_:1;
  BOOL useCustomTheme_:1;
  BOOL useSystemThemeByDefault_:1;
  NSString* customThemeName;
  NSString* customThemeId;
  NSString* customThemeUpdateUrl;
}
- (BOOL) hasUseCustomTheme;
- (BOOL) hasUseSystemThemeByDefault;
- (BOOL) hasCustomThemeName;
- (BOOL) hasCustomThemeId;
- (BOOL) hasCustomThemeUpdateUrl;
- (BOOL) useCustomTheme;
- (BOOL) useSystemThemeByDefault;
@property (readonly, retain) NSString* customThemeName;
@property (readonly, retain) NSString* customThemeId;
@property (readonly, retain) NSString* customThemeUpdateUrl;

+ (ThemeSpecifics*) defaultInstance;
- (ThemeSpecifics*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ThemeSpecifics_Builder*) builder;
+ (ThemeSpecifics_Builder*) builder;
+ (ThemeSpecifics_Builder*) builderWithPrototype:(ThemeSpecifics*) prototype;

+ (ThemeSpecifics*) parseFromData:(NSData*) data;
+ (ThemeSpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ThemeSpecifics*) parseFromInputStream:(NSInputStream*) input;
+ (ThemeSpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ThemeSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ThemeSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ThemeSpecifics_Builder : PBGeneratedMessage_Builder {
@private
  ThemeSpecifics* result;
}

- (ThemeSpecifics*) defaultInstance;

- (ThemeSpecifics_Builder*) clear;
- (ThemeSpecifics_Builder*) clone;

- (ThemeSpecifics*) build;
- (ThemeSpecifics*) buildPartial;

- (ThemeSpecifics_Builder*) mergeFrom:(ThemeSpecifics*) other;
- (ThemeSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ThemeSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUseCustomTheme;
- (BOOL) useCustomTheme;
- (ThemeSpecifics_Builder*) setUseCustomTheme:(BOOL) value;
- (ThemeSpecifics_Builder*) clearUseCustomTheme;

- (BOOL) hasUseSystemThemeByDefault;
- (BOOL) useSystemThemeByDefault;
- (ThemeSpecifics_Builder*) setUseSystemThemeByDefault:(BOOL) value;
- (ThemeSpecifics_Builder*) clearUseSystemThemeByDefault;

- (BOOL) hasCustomThemeName;
- (NSString*) customThemeName;
- (ThemeSpecifics_Builder*) setCustomThemeName:(NSString*) value;
- (ThemeSpecifics_Builder*) clearCustomThemeName;

- (BOOL) hasCustomThemeId;
- (NSString*) customThemeId;
- (ThemeSpecifics_Builder*) setCustomThemeId:(NSString*) value;
- (ThemeSpecifics_Builder*) clearCustomThemeId;

- (BOOL) hasCustomThemeUpdateUrl;
- (NSString*) customThemeUpdateUrl;
- (ThemeSpecifics_Builder*) setCustomThemeUpdateUrl:(NSString*) value;
- (ThemeSpecifics_Builder*) clearCustomThemeUpdateUrl;
@end

