// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class TypedUrlSpecifics;
@class TypedUrlSpecifics_Builder;

@interface TypedUrlSpecificsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface TypedUrlSpecifics : PBGeneratedMessage {
@private
  BOOL hasHidden_:1;
  BOOL hasUrl_:1;
  BOOL hasTitle_:1;
  BOOL hidden_:1;
  NSString* url;
  NSString* title;
  NSMutableArray* mutableVisitsList;
  int32_t visitsMemoizedSerializedSize;
  NSMutableArray* mutableVisitTransitionsList;
  int32_t visitTransitionsMemoizedSerializedSize;
}
- (BOOL) hasUrl;
- (BOOL) hasTitle;
- (BOOL) hasHidden;
@property (readonly, retain) NSString* url;
@property (readonly, retain) NSString* title;
- (BOOL) hidden;
- (NSArray*) visitsList;
- (int64_t) visitsAtIndex:(int32_t) index;
- (NSArray*) visitTransitionsList;
- (int32_t) visitTransitionsAtIndex:(int32_t) index;

+ (TypedUrlSpecifics*) defaultInstance;
- (TypedUrlSpecifics*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TypedUrlSpecifics_Builder*) builder;
+ (TypedUrlSpecifics_Builder*) builder;
+ (TypedUrlSpecifics_Builder*) builderWithPrototype:(TypedUrlSpecifics*) prototype;

+ (TypedUrlSpecifics*) parseFromData:(NSData*) data;
+ (TypedUrlSpecifics*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TypedUrlSpecifics*) parseFromInputStream:(NSInputStream*) input;
+ (TypedUrlSpecifics*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TypedUrlSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TypedUrlSpecifics*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TypedUrlSpecifics_Builder : PBGeneratedMessage_Builder {
@private
  TypedUrlSpecifics* result;
}

- (TypedUrlSpecifics*) defaultInstance;

- (TypedUrlSpecifics_Builder*) clear;
- (TypedUrlSpecifics_Builder*) clone;

- (TypedUrlSpecifics*) build;
- (TypedUrlSpecifics*) buildPartial;

- (TypedUrlSpecifics_Builder*) mergeFrom:(TypedUrlSpecifics*) other;
- (TypedUrlSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TypedUrlSpecifics_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUrl;
- (NSString*) url;
- (TypedUrlSpecifics_Builder*) setUrl:(NSString*) value;
- (TypedUrlSpecifics_Builder*) clearUrl;

- (BOOL) hasTitle;
- (NSString*) title;
- (TypedUrlSpecifics_Builder*) setTitle:(NSString*) value;
- (TypedUrlSpecifics_Builder*) clearTitle;

- (BOOL) hasHidden;
- (BOOL) hidden;
- (TypedUrlSpecifics_Builder*) setHidden:(BOOL) value;
- (TypedUrlSpecifics_Builder*) clearHidden;

- (NSArray*) visitsList;
- (int64_t) visitsAtIndex:(int32_t) index;
- (TypedUrlSpecifics_Builder*) replaceVisitsAtIndex:(int32_t) index with:(int64_t) value;
- (TypedUrlSpecifics_Builder*) addVisits:(int64_t) value;
- (TypedUrlSpecifics_Builder*) addAllVisits:(NSArray*) values;
- (TypedUrlSpecifics_Builder*) clearVisitsList;

- (NSArray*) visitTransitionsList;
- (int32_t) visitTransitionsAtIndex:(int32_t) index;
- (TypedUrlSpecifics_Builder*) replaceVisitTransitionsAtIndex:(int32_t) index with:(int32_t) value;
- (TypedUrlSpecifics_Builder*) addVisitTransitions:(int32_t) value;
- (TypedUrlSpecifics_Builder*) addAllVisitTransitions:(NSArray*) values;
- (TypedUrlSpecifics_Builder*) clearVisitTransitionsList;
@end

